Commit the latest version.

diff --git a/bin/applyflags b/bin/applyflags
--- a/bin/applyflags
+++ b/bin/applyflags
@@ -1,36 +1,37 @@
-#!/bin/sh
+#!/bin/bash
 
-#
-# See setup for user tweakables.
-#
-. $1/setup >/dev/null 2>&1
+# generate flags for apply.pl - from various pieces ...
+# highly dependent on a custom environment ...
 
-echo -n "--distro=$DISTRO"
+bindir=$1
 
-if test -d $OOBUILDDIR/binfilter ; then
-	echo -n " --distro=Binfilter"
+if test "z$bindir" == "z"; then
+    echo "Serious error - requires path to bindir";
+    exit 1;
 fi
 
+cd $bindir
+source setup >& /dev/null
+
+echo -n "--distro=$DISTRO";
+if test -d $OOBUILDDIR/binfilter; then
+    echo -n " --distro=Binfilter";
+fi
 if test -d $OOBUILDDIR/zlib; then
-	echo -n " --distro=System"
+    echo -n " --distro=System";
 fi
-
-if test -d $OOBUILDDIR/sdk_oo ; then
-	echo -n " --distro=Sdk"
+if test -d $OOBUILDDIR/sdk_oo; then
+    echo -n " --distro=Sdk";
 fi
-
-if grep localize.sdf $OOBUILDDIR/sw/source/ui/app/localize.sdf > /dev/null 2>&1 ; then
-	echo -n " --distro=Localize"
-fi
-
 if test -d $OOBUILDDIR/swext ; then
-	echo -n " --distro=swext"
+    echo -n " --distro=swext";
 fi
-
+if grep localize.sdf $OOBUILDDIR/sw/source/ui/app/localize.sdf > /dev/null 2>&1 ; then
+    echo -n " --distro=Localize";
+fi
 if test -n "$OOO_ADDITIONAL_SECTIONS" ; then
-	echo -n " --additional-sections=$OOO_ADDITIONAL_SECTIONS"
+    echo -n " --additional-sections=$OOO_ADDITIONAL_SECTIONS";
 fi
-
 if test "z$PIECE" != "z"; then
-	echo -n " --pieces --distro=Piece"
-fi
+    echo -n " --pieces --distro=Piece";
+fi ;
