2004-03-15  Michael Meeks  <michael@ximian.com>
* bin/setup.in, configure.in, bin/build-ooo:
add several win32 conditionals.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -206,8 +206,10 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 			$TOOLSDIR/patches/apply.pl $TOOLSDIR/patches/$CVSTAG $OOBUILDDIR --distro=$DISTRO -R || exit 1;
 		fi
 
-		echo "Removing custom icons";
-		$TOOLSDIR/bin/scale-icons $OOBUILDDIR --remove || exit 1;
+		if test "z$ENABLE_WIN32" = "z"; then
+			echo "Removing custom icons";
+			$TOOLSDIR/bin/scale-icons $OOBUILDDIR --remove || exit 1;
+		fi
 
 		echo "Poking resource builds";
 		find $OOBUILDDIR/*/*.pro -name '*.dpr' -exec rm {} \;
@@ -252,9 +254,11 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 		$TOOLSDIR/patches/apply.pl $TOOLSDIR/patches/$CVSTAG $OOBUILDDIR --distro=$DISTRO -f || exit 1;
 	fi
 
-	echo "Installing / scaling icons";
-	$TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
-	echo "done icon scaling";
+	if test "z$ENABLE_WIN32" = "z"; then
+		echo "Installing / scaling icons";
+		$TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
+		echo "done icon scaling";
+	fi
 
 	cp -Rvf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
 	echo "Copied new artwork into the tree";
