Double unpack ODMA into ucb/source/ucp/odma etc.
* bin/build-ooo: double unpack ODMA into
ucb/source/ucp/odma etc.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -133,9 +133,11 @@ cd $BUILDDIR
 
 UNICOWS_SRC=$SRCDIR/unicows.exe;
 DBGINST_SRC=$SRCDIR/dbghinst.EXE;
+ODMA_SRC=$SRCDIR/5_11_98Odma20.zip;
 if test "z$BUILD_WIN32" != "z"; then
     check-file $UNICOWS_SRC
     check-file $DBGINST_SRC
+    check-file $ODMA_SRC
 fi
 
 if test "z$ENABLE_JAVA" = "zyes" &&
@@ -299,29 +301,55 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 	fi
 
 	# Win32 prerequisites ...
-	cd $BUILDDIR;
 	if test "z$BUILD_WIN32" != "z"; then
-	    # dbghelp
-	    echo -n "Extracting dbghelp "
-	    cabextract -q $DBGINST_SRC
-	    TARGET=dbghelp.exe
+
+	    # ODMA
+	    cd $BUILDDIR;
+	    echo -n "Extracting ODMA SDK "
+	    unzip $ODMA_SRC
+	    TARGET=Odma20.zip
 	    if test ! -f $TARGET; then
 		echo "failed";
 		exit 1;
 	    fi
-	    unzip -o $TARGET
-	    cp -af x86/* $OOBUILDDIR/external/dbghelp
+	    DEST=$OOBUILDDIR/ucb/source/ucp/odma
+	    mkdir -p $DEST
+	    cd $DEST
+	    unzip -o $BUILDDIR/$TARGET
 	    echo "done";
 
-	    # unicows
-	    echo -n "Extracting unicows "
-	    cabextract -q $UNICOWS_SRC
-	    TARGET=unicows.dll
-	    if test ! -f $TARGET; then
-		echo "failed";
-		exit 1;
+	    # dbghelp
+	    cd $BUILDDIR;
+	    if test !-f $OOBUILDDIR/external/dbghelp/DbgHelp.Dll; then
+		echo -n "Extracting dbghelp "
+		cabextract -q $DBGINST_SRC
+		TARGET=dbghelp.exe
+		if test ! -f $TARGET; then
+		    echo "failed";
+		    exit 1;
+		fi
+		unzip -o $TARGET
+		cp -af x86/* $OOBUILDDIR/external/dbghelp
+		echo "done";
+	    else
+		echo "Already have dbghelp";
 	    fi
-	    cp -af $TARGET $OOBUILDDIR/external/unicows
+
+	    # unicows
+	    cd $BUILDDIR;
+	    if test !-f $OOBUILDDIR/external/dbghelp/unicows.dll; then
+		echo -n "Extracting unicows "
+		cabextract -q $UNICOWS_SRC
+		TARGET=unicows.dll
+		if test ! -f $TARGET; then
+		    echo "failed";
+		    exit 1;
+		fi
+		cp -af $TARGET $OOBUILDDIR/external/unicows
+		echo "done";
+	    else
+		echo "Already have unicows";
+	    fi
 
 	    # vcp bits (?)
 	    mkdir -p $OOBUILDDIR/external/msvcp71
