Make it compile again -- hope it doesn't break for others

diff --git a/bin/build-galleries b/bin/build-galleries
--- a/bin/build-galleries
+++ b/bin/build-galleries
@@ -22,15 +22,23 @@ fi
 if test "$BUILD_OOO_GAL_FROM_OPENCLIPART" = "no" -a \
         "$VENDORNAME" != "Novell" ; then
     echo "    ${0##*/}: Nothing to do"
-    exit 0;
+    exit 0
 fi
 
-if ! test -x /usr/X11R6/bin/Xvfb ; then
+XVFB=`which Xvfb 2>/dev/null`
+if ! test -x "$XVFB"; then
+	# Fall back to some default locations if which didn't work
+	XVFB=/usr/X11R6/bin/Xvfb
+	if ! test -x "$XVFB"; then
+		XVFB=/usr/bin/Xvfb
+	fi
+fi
+if ! test -x "$XVFB" ; then
     if test "$BUILD_OOO_GAL_FROM_OPENCLIPART" = "yes" ; then
-	echo "Error: /usr/X11R6/bin/Xvfb not found" >&2
+	echo "Error: $XVFB not found" >&2
 	exit 1
     else
-	echo "Warning: /usr/X11R6/bin/Xvfb not found,"
+	echo "Warning: $XVFB not found,"
 	echo "         skipping the optional gallery stuff..."
 	exit 0;
     fi
@@ -115,7 +123,7 @@ while test "$XDISPLAY" != "108" ; do
 	if [ ! -f /tmp/.X$XDISPLAY-lock ]; then
 		echo "    trying display :$XDISPLAY ..."
 		sleep 2s
-		/usr/X11R6/bin/Xvfb -ac :$XDISPLAY >& /dev/null &
+		$XVFB -ac :$XDISPLAY >& /dev/null &
 		trap "kill $! > /dev/null 2>&1 || true" EXIT
 		# let server to start
 		sleep 10s 
