Add.
* patches/RC3_030721/buildable: add.

* bin/latest-patchset: check for a 'buildable'
stamp in each patch directory, to return the latest
known-buildable tree. To get the very latest use
--devel.

* bin/build-ooo (check-tarball): remove
anachronistic bb_get stuff.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -89,7 +89,6 @@ BINUTILS_UNTAR_OPTIONS=jxf
 if test ${CVSTAG:0:3} == 'OOO'; then
     JDK_VER=j2sdk1.3.1
     JDK_TARBALL=j2sdk-1.3.1-FCS-linux-i386.tar.bz2
-    JDK_REPO_NAME=j2sdk-1.3.1-FCS-linux-i386.tar.bz2-1
     JDK_UNTAR_OPTIONS=jxf
 
     OOO_ICONS_VER=ooo-icons-OOO_1_0_3-1
@@ -113,7 +112,6 @@ else
 
     JDK_VER=j2sdk1.4.1
     JDK_TARBALL=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2
-    JDK_REPO_NAME=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2-2
     JDK_UNTAR_OPTIONS=jxf
 
     OOO_ICONS_VER=ooo-icons-RC3-1
@@ -123,22 +121,14 @@ OOO_ICONS_TARBALL=$OOO_ICONS_VER.tar.gz
 OOO_ICONS_UNTAR_OPTIONS=xzf
 
 OOO_TARBALL="$CVSTAG.tar.bz2"
-OOO_REPO_NAME="$CVSTAG.tar.bz2-1"
 OOO_UNTAR_OPTIONS=jxf
 
-# get-tarball TARBALLFILENAME 
-# Sees if a tarball exists and if not gets it from build-buddy
-get-tarball ()
+check-tarball ()
 {
-    tarball=$1
-    reponame=$2
-    if test "z$reponame" = "z"; then
-	reponame="$tarball"-1
-    fi
-    echo -n "Looking for $tarball... "
-    if test ! -f $tarball; then
-	echo "no --- Getting $reponame from build-buddy"
-	bb_get $reponame || exit 1
+    echo -n "Looking for $1 ... ";
+    if test ! -f $1; then
+	echo "missing the $1 archive; run './download'"
+	exit 1;
     else
 	echo "ok"
     fi
@@ -149,11 +139,11 @@ if test "z$WITH_SRC" = "z"; then
     cd $SRCDIR
 
     echo "Checking for source packages in $SRCDIR";
-    get-tarball $GCC_TARBALL
-    get-tarball $BINUTILS_TARBALL
-    get-tarball $JDK_TARBALL $JDK_REPO_NAME
-    get-tarball $OOO_TARBALL $OOO_REPO_NAME
-    get-tarball $OOO_ICONS_TARBALL
+    check-tarball $GCC_TARBALL
+    check-tarball $BINUTILS_TARBALL
+    check-tarball $JDK_TARBALL
+    check-tarball $OOO_TARBALL
+    check-tarball $OOO_ICONS_TARBALL
 
     if test ! -f $GCC_TARBALL; then
 	echo "You need to put the relevant source packages into $SRCDIR before commencing the build";
