Use new Novell splash for win32.
* patches/OOO_1_1/novell-splash.diff,
* patches/OOO_1_1_1/apply: use new Novell splash
for win32.

* download.in, configure.in: update to ooo-icons -9,
re-work the way the icons URI is generated.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -342,6 +342,9 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 
 	cp -Rvf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
 	echo "Copied new artwork into the tree";
+
+	cp -vf $TOOLSDIR/fonts/opens___.ttf $OOBUILDDIR/extras/source/truetype/symbol || echo "font copy failed";
+	echo "Copied new opensymbol font into the tree";
 	
 	find $OOBUILDDIR -name '*.src' -exec touch {} \;;
 
