Allow to build and install the OOo galleries out of box; it is enough to use the new --with-openclipart configure switch, see doc/openclipart.
* configure.in, download.in, bin/build-galleries, bin/ooinstall,
bin/unpack, doc/gallery.txt, doc/openclipart.txt: allow to build
and install the OOo galleries out of box; it is enough to use
the new --with-openclipart configure switch, see doc/openclipart.txt
for more details

diff --git a/bin/build-galleries b/bin/build-galleries
--- a/bin/build-galleries
+++ b/bin/build-galleries
@@ -1,55 +1,93 @@
 #!/bin/sh
 
-# this script is useful to generate galleries for OOo from openclipart
-# source tarball that it available at
+# this script is useful to generate galleries for OOo from Open Clip Art
+# Library source tarball that it available at
 # http://www.openclipart.org/downloads/index.php
 
-# It requires the gengal binary that is actually available in OOo only when
-# built with ooo-build
-GAL_BIN=/usr/lib/ooo-2.0/program/gengal
+#
+# See setup for user tweakables.
+#
+. ./setup
 
-# version of openclipart source tarball
-OCA_VER=0.12
-# where to install the generated bitmaps
-GAL_SRC_DIR=/usr/share/openclipart
-#GAL_SRC_DIR=/tmp/gallery.bitmaps
 # where to install the OOo-related files (thumbnails & points at the files, ...)
-GAL_DIR=/usr/lib/ooo-2.0/share/gallery
-#GAL_DIR=/tmp/gallery.ooo
-OODESTDIR=/var/tmp
-# start number for the OOo-related files
+if test "z$1" != "z"; then
+    OOINSTDIR="$1"
+fi
+
+if test "z$OPENCLIPART_DIR" = "z" ; then
+    # where to install the generated bitmaps
+    OPENCLIPART_DIR=$OODESTDIR/usr/share/openclipart
+    # where are the unpackaged openclipart sources
+    OPENCLIPART_SRCDIR=$BUILDDIR/openclipart-$OPENCLIPART_VER
+fi
+
+# where to install the OOo-related files (thumbnails & points at the files, ...)
+GAL_DIR=$OOINSTDIR/share/gallery
+# It requires the gengal binary
+# The binary is actually available in OOo only when built with ooo-build
+GAL_BIN=$OOINSTDIR/program/gengal
+# start number for the new galleries
 GAL_NUMBER_FROM=70
 
-echo "Unpacking openclipart sources..."
+if (! test -e $GAL_BIN); then
+    echo "Cannot find $GAL_BIN; make sure you installed OOo first"
+    exit 1;
+fi
 
-rm -rf openclipart-$OCA_VER
-tar -xjf openclipart-$OCA_VER.tar.bz2
+if test "z$OPENCLIPART_VER" != "z" ; then
 
-echo "Generating .png files..."
+    echo "Generating .png files..."
 
-rm -rf $OODESTDIR$GAL_SRC_DIR
-for pict_svg in `find openclipart-$OCA_VER -name "*.svg" -type f ` ; do
-    pict_dir=${pict_svg#openclipart-$OCA_VER/}
-    pict_dir=${pict_dir%/*}
-    pict_png=${pict_svg##*/}
-    pict_png=${pict_png%.svg}.png
-    mkdir -p $OODESTDIR$GAL_SRC_DIR/$pict_dir
-    inkscape -f $pict_svg -e $OODESTDIR$GAL_SRC_DIR/$pict_dir/$pict_png
-done
+    if test ! -d $OPENCLIPART_SRCDIR ; then
+	echo "Cannot find Open Clip Art sources in $OPENCLIPART_SRCDIR"
+        echo "Try to run ./download and ./bin/unpack"
+	exit 1;
+    fi
 
-echo "Removing some blacklisted files..."
+    rm -rf $OPENCLIPART_DIR
+    for pict_svg in `find $OPENCLIPART_SRCDIR -name "*.svg" -type f ` ; do
+	pict_dir=${pict_svg#$OPENCLIPART_SRCDIR/}
+        pict_dir=${pict_dir%/*}
+	pict_png=${pict_svg##*/}
+        pict_png=${pict_png%.svg}.png
+	mkdir -p $OPENCLIPART_DIR/$pict_dir
+        inkscape -f $pict_svg -e $OPENCLIPART_DIR/$pict_dir/$pict_png
+    done
 
-for path in signs_and_symbols/flags \
-	    unsorted ; do
-    echo "  remove $path"
-    rm -rf $OODESTDIR$GAL_SRC_DIR/$path
-done
+    echo "Removing some blacklisted files..."
 
-echo "done"
+    for path in signs_and_symbols/flags \
+		unsorted ; do
+	echo "  remove $path"
+	rm -rf $OPENCLIPART_DIR/$path
+    done
 
-rm -rf "$OODESTDIR$GAL_DIR"
-mkdir -p "$OODESTDIR$GAL_DIR"
-for dir in `find $OODESTDIR$GAL_SRC_DIR -mindepth 1 -maxdepth 1 -type d | LC_CTYPE=C sort` ; do
+    #file list
+    if test "z$OODESTDIR" != "z" ; then
+	rm -f $BUILDDIR/openclipart.txt
+	for dir in `find $OPENCLIPART_DIR -type d` ; do
+	    echo "%dir ${dir#$OODESTDIR}" >>$BUILDDIR/openclipart.txt
+	done
+	for file in `find $OPENCLIPART_DIR -type f` ; do
+	    echo "${file#$OODESTDIR}" >>$BUILDDIR/openclipart.txt
+	done
+    fi
+
+    echo "done"
+
+fi
+
+if test ! -e /tmp/.X0-lock && which Xvfb >/dev/null 2>&1 ; then
+    # X server probably is not available, try to use Xvfb
+    export DISPLAY=":98"
+    Xvfb $DISPLAY >& /Xvfb.log &
+    trap "kill $! || true" EXIT
+    # let server to start
+    sleep 10
+fi
+
+mkdir -p "$GAL_DIR"
+for dir in `find $OPENCLIPART_DIR -mindepth 1 -maxdepth 1 -type d | LC_CTYPE=C sort` ; do
     # get the gallery name from the directory name
     # and make the first character uppercase
     gal_name=${dir##*/}
@@ -60,5 +98,20 @@ for dir in `find $OODESTDIR$GAL_SRC_DIR -mindepth 1 -maxdepth 1 -type d | LC_CTY
     gal_name=$gal_name_first_char$gal_name_rest
 
     echo "Doing gallery $gal_name..."
-    $GAL_BIN --name "$gal_name" --path "$OODESTDIR$GAL_DIR" --destdir "$OODESTDIR" --number-from "$GAL_NUMBER_FROM" `find $dir -name "*.png"`
+    # xargs is necessary because I 
+    find $dir -name "*.png" | { xargs $GAL_BIN --name "$gal_name" --path "$GAL_DIR" --destdir "$OODESTDIR" --number-from "$GAL_NUMBER_FROM" || exit 1; }
 done
+
+# guess the filelist
+if test "z$OODESTDIR" != "z" ; then
+    gal_num=$GAL_NUMBER_FROM
+    rm -f $BUILDDIR/galleries.txt
+    while test -f $GAL_DIR/sg$gal_num.sdg -a \
+               -f $GAL_DIR/sg$gal_num.sdv -a \
+	       -f $GAL_DIR/sg$gal_num.thm ; do
+	echo ${GAL_DIR#$OODESTDIR}/sg$gal_num.sdg >>$BUILDDIR/galleries.txt
+	echo ${GAL_DIR#$OODESTDIR}/sg$gal_num.sdv >>$BUILDDIR/galleries.txt
+	echo ${GAL_DIR#$OODESTDIR}/sg$gal_num.thm >>$BUILDDIR/galleries.txt
+	gal_num=$(($gal_num + 1))
+    done
+fi
