Rename from setup, pre-process in configure.
* configure.in,
* bin/setup.in: rename from setup, pre-process
in configure.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -91,6 +91,8 @@ if test ${CVSTAG:0:3} == 'OOO'; then
     JDK_TARBALL=j2sdk-1.3.1-FCS-linux-i386.tar.bz2
     JDK_REPO_NAME=j2sdk-1.3.1-FCS-linux-i386.tar.bz2-1
     JDK_UNTAR_OPTIONS=jxf
+
+    OOO_ICONS_VER=ooo-icons-OOO_1_0_3-1
 else
 
     if (! `pkg-config --exists 'libart-2.0 >= 2.3.13'`); then
@@ -113,7 +115,12 @@ else
     JDK_TARBALL=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2
     JDK_REPO_NAME=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2-2
     JDK_UNTAR_OPTIONS=jxf
+
+    OOO_ICONS_VER=ooo-icons-RC3-1
 fi
+
+OOO_ICONS_TARBALL=$OOO_ICONS_VER.tar.gz
+OOO_ICONS_UNTAR_OPTIONS=xzf
 
 OOO_TARBALL="$CVSTAG.tar.bz2"
 OOO_REPO_NAME="$CVSTAG.tar.bz2-1"
@@ -146,6 +153,7 @@ if test "z$BUILD_VERSION" = "z"; then
     get-tarball $BINUTILS_TARBALL
     get-tarball $JDK_TARBALL $JDK_REPO_NAME
     get-tarball $OOO_TARBALL $OOO_REPO_NAME
+    get-tarball $OOO_ICONS_TARBALL
 
     if test ! -f $GCC_TARBALL; then
 	echo "You need to put the relevant source packages into $SRCDIR before commencing the build";
@@ -198,6 +206,21 @@ else
 fi
 # -- cut --
 
+PKG_VER=$OOO_ICONS_VER
+
+# -- evil cut --
+if test -f $BUILDDIR/$PKG_VER/$STAMP; then
+	echo "Skipping $PKG_VER";
+else
+	echo "Building $PKG_VER";
+	cd $BUILDDIR
+	if test "z$BUILD_VERSION" = "z"; then
+	    tar $OOO_ICONS_UNTAR_OPTIONS $SRCDIR/$OOO_ICONS_TARBALL || exit 1;
+	fi
+	touch $BUILDDIR/$PKG_VER/$STAMP || exit 1;
+fi
+# -- cut --
+
 # build gcc
 PKG_VER=$GCC_VER
 
@@ -236,9 +259,6 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 
 		echo "Removing custom icons";
 		$TOOLSDIR/bin/scale-icons $OOBUILDDIR --remove || exit 1;
-		if test -f $TOOLSDIR/icons/ChangeLog; then
-			$TOOLSDIR/bin/install-icons $CVSTAG $OOBUILDDIR $TOOLSDIR --remove || exit 1;
-		fi
 
 		echo "Poking resource builds";
 		find $OOBUILDDIR -name '*.dpr' -exec rm {} \;
@@ -274,9 +294,6 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 	if test "z$2" = "z--nopatch"; then
 		echo "Skipping patching";
 	else
-#		echo "Installing link maps"
-#		$TOOLSDIR/bin/install-maps $OOBUILDDIR $TOOLSDIR gcc3 || exit 1;
-
 		echo "Re-applying patches"
 		$TOOLSDIR/patches/apply.pl $TOOLSDIR/patches/$CVSTAG $OOBUILDDIR -f || exit 1;
 	fi
@@ -284,11 +301,9 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 	echo "Installing / scaling icons";
 	$TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
 	echo "done icon scaling";
-	if test -f $TOOLSDIR/icons/ChangeLog; then
-	    $TOOLSDIR/bin/install-icons $CVSTAG $OOBUILDDIR $TOOLSDIR || exit 1;
-	else
-	    cp -avf $TOOLSDIR/icons/* $OOBUILDDIR || echo "Icon copy failed";
-	fi
+
+	cp -avf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
+	echo "Copied new artwork into the tree";
 	
 	find $OOBUILDDIR -name '*.src' -exec touch {} \;;
 
