Download/unpack/install unicows.
* download.in, bin/build-ooo: download/unpack/install
unicows.dll and dbghelp.dll.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -69,7 +69,16 @@ check-tarball ()
     fi
 }
 
-
+check-file ()
+{
+    echo -n "Looking for $1 ... ";
+    if test ! -f $1; then
+	echo "missing required archive; run ./download'";
+	exit 1;
+    else
+	echo "ok"
+    fi
+}
 
 if test "z$WITH_SRC" = "z"; then
     mkdir -p $SRCDIR
@@ -115,6 +124,12 @@ fi
 
 cd $BUILDDIR
 
+UNICOWS_SRC=$SRCDIR/unicows.exe;
+DBGINST_SRC=$SRCDIR/dbghinst.exe;
+if test "z$BUILD_WIN32" != "z"; then
+    check-file $UNICOWS_SRC
+    check-file $DBGINST_SRC
+fi
 
 if test "z$ENABLE_JAVA" = "zyes" &&
    test "z$JDK_HOME" = "z"; then
@@ -276,6 +291,35 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 		if test ! -d "$BUILDDIR/$CVSTAG"; then
 			echo "Missing the main OO.o source tree";
 		fi
+	fi
+
+	# Win32 prerequisites ...
+	cd $BUILDDIR;
+	if test "z$BUILD_WIN32" != "z"; then
+	    # dbghelp
+	    echo -n "Extracting dbghelp "
+	    cabextract -q $DBGINST_SRC
+	    TARGET=dbghelp.exe
+	    if test ! -f $TARGET; then
+		echo "failed";
+		exit 1;
+	    fi
+	    unzip -o $TARGET
+	    cp -af x86/* $OOBUILDDIR/external/dbghelp
+	    echo "done";
+
+	    # unicows
+	    echo -n "Extracting unicows "
+	    cabextract -q $UNICOWS_SRC
+	    TARGET=unicows.dll
+	    if test ! -f $TARGET; then
+		echo "failed";
+		exit 1;
+	    fi
+	    cp -af $TARGET $OOBUILDDIR/external/unicows
+
+	    # vcp bits (?)
+	    mkdir -p $OOBUILDDIR/external/msvcp71
 	fi
 
 	cd $OOBUILDDIR
