Check for Xvfb; skip optional Novell gallery stuff when Xvfb is not found; try to run Xvfb max 10-times to avoid potential infinite loop
* bin/build-galleries: check for Xvfb; skip optional Novell gallery
stuff when Xvfb is not found; try to run Xvfb max 10-times to
avoid potential infinite loop

diff --git a/bin/build-galleries b/bin/build-galleries
--- a/bin/build-galleries
+++ b/bin/build-galleries
@@ -25,6 +25,17 @@ if test "$BUILD_OOO_GAL_FROM_OPENCLIPART" = "no" -a \
     exit 0;
 fi
 
+if ! test -x /usr/X11R6/bin/Xvfb ; then
+    if test "$BUILD_OOO_GAL_FROM_OPENCLIPART" = "yes" ; then
+	echo "Error: /usr/X11R6/bin/Xvfb not found" >&2
+	exit 1
+    else
+	echo "Warning: /usr/X11R6/bin/Xvfb not found,"
+	echo "         skipping the optional gallery stuff..."
+	exit 0;
+    fi
+fi
+
 if test "z$OPENCLIPART_DIR" = "z" ; then
     # where to install the generated bitmaps
     OPENCLIPART_DIR=$OODESTDIR/usr/share/openclipart
@@ -99,8 +110,10 @@ fi
 
 XDISPLAY=98
 echo "Starting Xvfb..."
-while /bin/true; do 
+# try only 10-times to avoid infinite loop
+while test "$XDISPLAY" != "108" ; do 
 	if [ ! -f /tmp/.X$XDISPLAY-lock ]; then
+		echo "    trying display :$XDISPLAY ..."
 		sleep 2s
 		/usr/X11R6/bin/Xvfb -ac :$XDISPLAY >& /dev/null &
 		trap "kill $! > /dev/null 2>&1 || true" EXIT
@@ -112,6 +125,12 @@ while /bin/true; do
 	fi
 	XDISPLAY=$(($XDISPLAY+1))
 done
+
+if ! test -f /tmp/.X$XDISPLAY-lock ; then
+    echo "Error: Unable to start Xvfb" >&2
+    exit 1
+fi
+
 export DISPLAY=":$XDISPLAY"
 echo "Using DISPLAY="$DISPLAY
 echo "Xvfb processes:"
