Disable ODMA download/unpack/patch
* download.in, patches/OOO_1_1_1/apply,
* bin/build-ooo: disable ODMA download/unpack/patch

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -133,11 +133,11 @@ cd $BUILDDIR
 
 UNICOWS_SRC=$SRCDIR/unicows.exe;
 DBGINST_SRC=$SRCDIR/dbghinst.EXE;
-ODMA_SRC=$SRCDIR/5_11_98Odma20.zip;
+# ODMA_SRC=$SRCDIR/5_11_98Odma20.zip;
 if test "z$BUILD_WIN32" != "z"; then
     check-file $UNICOWS_SRC
     check-file $DBGINST_SRC
-    check-file $ODMA_SRC
+#    check-file $ODMA_SRC
 fi
 
 if test "z$ENABLE_JAVA" = "zyes" &&
@@ -304,23 +304,23 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 	if test "z$BUILD_WIN32" != "z"; then
 
 	    # ODMA
-	    cd $BUILDDIR;
-	    DEST=$OOBUILDDIR/ucb/source/ucp/odma
-	    if test ! -f $DEST/ODMA.H; then
-		echo -n "Extracting ODMA SDK "
-		unzip -o $ODMA_SRC
-		TARGET=Odma20.exe
-		if test ! -f $TARGET; then
-		    echo "failed";
-		    exit 1;
-		fi
-		mkdir -p $DEST
-		cd $DEST
-		unzip -o $BUILDDIR/$TARGET
-		echo "done";
-	    else
-		echo "Already have ODMA SDK";
-	    fi
+#	    cd $BUILDDIR;
+#	    DEST=$OOBUILDDIR/ucb/source/ucp/odma
+#	    if test ! -f $DEST/ODMA.H; then
+#		echo -n "Extracting ODMA SDK "
+#		unzip -o $ODMA_SRC
+#		TARGET=Odma20.exe
+#		if test ! -f $TARGET; then
+#		    echo "failed";
+#		    exit 1;
+#		fi
+#		mkdir -p $DEST
+#		cd $DEST
+#		unzip -o $BUILDDIR/$TARGET
+#		echo "done";
+#	    else
+#		echo "Already have ODMA SDK";
+#	    fi
 
 	    # dbghelp
 	    cd $BUILDDIR;
