Add
* patches/src680/win32-build-fixes.diff,
patches/src680/win32-msvs-2003-configure.diff: add
* Makefile.shared, bin/build-ooo, bin/setup.in,
patches/src680/win32-gw-send-mail.diff,
patches/src680-m74/apply: changes for the win32 build

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -5,10 +5,12 @@
 #
 . ./setup
 
-if ! test -f /proc/kcore; then
-    echo "Looks like proc isn't mounted - this means almost certain"
-    echo "Java related weird build failure: please check /proc"
-    exit 1;
+if test "z$BUILD_WIN32" = "z"; then
+    if ! test -f /proc/kcore; then
+        echo "Looks like proc isn't mounted - this means almost certain"
+        echo "Java related weird build failure: please check /proc"
+        exit 1;
+    fi
 fi
 
 # configure
