Add check for mounted /proc
* bin/build-ooo: add check for mounted /proc

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -5,6 +5,12 @@
 #
 . ./setup
 
+if ! test -f /proc/kcore; then
+    echo "Looks like proc isn't mounted - this means almost certain"
+    echo "Java related weird build failure: please check /proc"
+    exit 1;
+fi
+
 # configure
 
 #  dmake security patch
@@ -21,6 +27,10 @@ autoconf || exit 1;
 if test "z$FORCE_GCC33" = "zYES"; then
 CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS CFLAGS= CXXFLAGS= CC=gcc33 CXX=g++33"
 fi
+
+echo "Env for configure:"
+set
+echo "Env for configure ends"
 
 eval ./configure "$CONFIGURE_OPTIONS" || exit 1;
 
