Add --with-jdk-home option that allows you to specify a JDK on your current system rather than use the downloaded one.
* configure.in: add --with-jdk-home option that
allows you to specify a JDK on your current system
rather than use the downloaded one.  Sets the
JDK_HOME variable on ./configure

* bin/build-ooo: various changes to see whether the
user specified --with-jdk-home and use that as
opposed to the downloaded JDK tarball.

* bin/setup.in: add JDK_HOME to PATH if it exists,
and add --with-jdk-home=$JDK_HOME to the OOo
configure script options through CONFIGURE_OPTIONS
if user specified --with-jdk-home at build-ooo
configure time

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -38,9 +38,13 @@ BINUTILS_UNTAR_OPTIONS=jxf
 BINUTILS_PATCH=$TOOLSDIR/patches/ld-2.13.2.1.diff
 
 if test "z$ENABLE_JAVA" = "zyes"; then
-    JDK_VER=j2sdk1.4.1
-    JDK_TARBALL=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2
-    JDK_UNTAR_OPTIONS=jxf
+    # If the user didn't specify the location of the JDK,
+    # use builtin/downloaded one
+    if test "z$JDK_HOME" = "z"; then
+        JDK_VER=j2sdk1.4.1
+        JDK_TARBALL=j2sdk-1.4.1-01-linux-i586-gcc3.2.tar.bz2
+        JDK_UNTAR_OPTIONS=jxf
+    fi
 fi
 
 OOO_ICONS_VER=ooo-icons-OOO_1_1-6
@@ -69,11 +73,12 @@ if test "z$WITH_SRC" = "z"; then
 
     echo "Checking for source packages in $SRCDIR";
     if test "z$SYSTEM_GCC" = "z"; then
-	check-tarball $GCC_TARBALL
-	check-tarball $BINUTILS_TARBALL
+        check-tarball $GCC_TARBALL
+        check-tarball $BINUTILS_TARBALL
     fi
-    if test "z$ENABLE_JAVA" = "zyes"; then
-	check-tarball $JDK_TARBALL
+    if test "z$ENABLE_JAVA" = "zyes" &&
+       test "z$JDK_HOME" = "z"; then
+        check-tarball $JDK_TARBALL
     fi
     check-tarball $OOO_TARBALL
     check-tarball $OOO_ICONS_TARBALL
@@ -86,22 +91,24 @@ if test "z$WITH_SRC" = "z"; then
     fi
 elif test "z$SYSTEM_GCC" = "z"; then
     if test "z$ENABLE_JAVA" = "zyes" &&
-       test ! -d "$BUILDDIR/$JDK_VER"; then
-	echo "Missing the Jdk";
+       test ! -d "$BUILDDIR/$JDK_VER" &&
+       test "z$JDK_HOME" = "z"; then
+        echo "Missing the JDK";
     fi
 
     if test ! -d "$BUILDDIR/$GCC_VER" ||
        test ! -d "$BUILDDIR/$OOO_ICONS_VER" ||
        test ! -d "$BUILDDIR/$BINUTILS_VER"; then
-       echo "Missing some of the helper source";
-       exit 1;
+        echo "Missing some of the helper source";
+        exit 1;
     fi
 fi
 
 cd $BUILDDIR
 
 
-if test "z$ENABLE_JAVA" = "zyes"; then
+if test "z$ENABLE_JAVA" = "zyes" &&
+   test "z$JDK_HOME" = "z"; then
     # unpack the Jdk
     PKG_VER=$JDK_VER
 
