Copy -Rvf not -a to avoid odd hard-linking issue.
* bin/build-ooo: copy -Rvf not -a to avoid odd
hard-linking issue.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -229,7 +229,7 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 	$TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
 	echo "done icon scaling";
 
-	cp -avf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
+	cp -Rvf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
 	echo "Copied new artwork into the tree";
 	
 	find $OOBUILDDIR -name '*.src' -exec touch {} \;;
