Unpack / work on 'scaled-icons.
* bin/build-ooo: unpack / work on
'scaled-icons.tar.gz'

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -51,6 +51,10 @@ OOO_ICONS_VER=ooo-icons-OOO_1_1-8
 OOO_ICONS_TARBALL=$OOO_ICONS_VER.tar.gz
 OOO_ICONS_UNTAR_OPTIONS=xzf
 
+OOO_SCALED_ICONS_VER=ooo-scaled-icons
+OOO_SCALED_ICONS_TARBALL=$OOO_ICONS_VER.tar.gz
+OOO_SCALED_ICONS_UNTAR_OPTIONS=xzf
+
 OOO_TARBALL="$CVSTAG.tar.bz2"
 OOO_UNTAR_OPTIONS=jxf
 
@@ -89,6 +93,11 @@ if test "z$WITH_SRC" = "z"; then
 	   exit 1
       fi
     fi
+
+    if test "z$ENABLE_WIN32" != "z"; then
+	check-tarball $OOO_SCALED_ICONS_TARBALL
+    fi
+
 elif test "z$SYSTEM_GCC" = "z"; then
     if test "z$ENABLE_JAVA" = "zyes" &&
        test ! -d "$BUILDDIR/$JDK_VER" &&
@@ -183,6 +192,23 @@ else
 fi
 # -- cut --
 
+PKG_VER=$OOO_SCALED_ICONS_VER
+
+# -- evil cut --
+if test "z$ENABLE_WIN32" != "z"; then
+    if test -f $BUILDDIR/$PKG_VER/$STAMP; then
+	echo "Skipping $PKG_VER";
+    else
+	echo "Building $PKG_VER";
+	cd $BUILDDIR
+	if test "z$WITH_SRC" = "z"; then
+	    tar $OOO_SCALED_ICONS_UNTAR_OPTIONS $SRCDIR/$OOO_SCALED_ICONS_TARBALL || exit 1;
+	fi
+	touch $BUILDDIR/$PKG_VER/$STAMP || exit 1;
+    fi
+fi
+# -- cut --
+
 # Checkout / Update source:
 if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 
@@ -258,6 +284,8 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 		echo "Installing / scaling icons";
 		$TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
 		echo "done icon scaling";
+	else
+	    cp -Rvf $BUILDDIR/$OOO_SCALED_ICONS_VER/* $OOBUILDDIR || echo "Scaled icon copy failed"
 	fi
 
 	cp -Rvf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
