Drop the bogus odma.
* patches/OOO_1_1/win32-odma.diff: drop the bogus
odma.h header.

diff --git a/bin/build-ooo b/bin/build-ooo
--- a/bin/build-ooo
+++ b/bin/build-ooo
@@ -305,18 +305,22 @@ if (test "z$2" = "z--checkout") || !(test -f $OOBUILDDIR/$STAMP); then
 
 	    # ODMA
 	    cd $BUILDDIR;
-	    echo -n "Extracting ODMA SDK "
-	    unzip $ODMA_SRC
-	    TARGET=Odma20.zip
-	    if test ! -f $TARGET; then
-		echo "failed";
-		exit 1;
-	    fi
 	    DEST=$OOBUILDDIR/ucb/source/ucp/odma
-	    mkdir -p $DEST
-	    cd $DEST
-	    unzip -o $BUILDDIR/$TARGET
-	    echo "done";
+	    if test !-f $DEST/ODMA.H; then
+		echo -n "Extracting ODMA SDK "
+		unzip $ODMA_SRC
+		TARGET=Odma20.zip
+		if test ! -f $TARGET; then
+		    echo "failed";
+		    exit 1;
+		fi
+		mkdir -p $DEST
+		cd $DEST
+		unzip -o $BUILDDIR/$TARGET
+		echo "done";
+	    else
+		echo "Already have ODMA SDK";
+	    fi
 
 	    # dbghelp
 	    cd $BUILDDIR;
