Rename from bin/git-merge-bases.
* bin/git-merge-gob: Rename from bin/git-merge-bases.
* bin/gob-update: Update.

diff --git a/bin/gob-update b/bin/gob-update
--- a/bin/gob-update
+++ b/bin/gob-update
@@ -14,8 +14,12 @@ master_branch=$1
 gob_bases=$(git-tag | grep '^gob-')
 if test -z "$gob_bases"
 then
-    echo 'cannot find any gob-* tag, aborting'
-    exit 1
+	echo 'cannot find any gob-* tag, aborting'
+	exit 1
 fi
 
-git-merge-bases --bases="$gob_bases" $master_branch
+git-merge-gob --bases="$gob_bases" $master_branch
+
+# Local Variables:
+# sh-basic-offset:8
+# End:
