Udpate for ooo300-m4
* patches/dev300/piece-desktop-m30.diff:
* patches/dev300/piece-desktop.diff:
* patches/dev300/apply: udpate for ooo300-m4

* ooo-build/bin/install-mono: rename the .config files to .dll.config
to be found by gacutil; also really removed .dlls and config files
after they are installed into GAC

diff --git a/bin/install-mono b/bin/install-mono
--- a/bin/install-mono
+++ b/bin/install-mono
@@ -52,24 +52,28 @@ done
 # at runtime.
 if test -z "$OODESTDIR" -o -n "$MONO_GAC_ROOT" ; then
     test -n "$MONO_GAC_ROOT" && gacutil_root="-root $OODESTDIR$MONO_GAC_ROOT" || gacutil_root=
-    for dll in ure/lib/cli_basetypes.dll \
-               ure/lib/cli_cppuhelper.dll \
-	       ure/lib/cli_uretypes.dll \
-	       basis$VERSION/program/cli_oootypes.dll \
-	       ure/lib/cli_uno_bridge.dll \
-	       ure/lib/cli_ure.dll ; do
-	gacutil $gacutil_root -i $OOINSTDIR/$dll -package $OOOINSTALLDIRNAME || exit 0
+    for dll_name in ure/lib/cli_basetypes \
+               ure/lib/cli_cppuhelper \
+	       ure/lib/cli_uretypes \
+	       basis$VERSION/program/cli_oootypes \
+	       ure/lib/cli_uno_bridge \
+	       ure/lib/cli_ure ; do
+	# create .config files with correct names
+	test -f $OOINSTDIR/$dll_name.config && mv $OOINSTDIR/$dll_name.config $OOINSTDIR/$dll_name.dll.config
+	gacutil $gacutil_root -i $OOINSTDIR/$dll_name.dll -package $OOOINSTALLDIRNAME || exit 0
 
 	# the original fixes are not longer needed
-	rm -f $OOINSTDIR/basis$VERSION/program/$dll
-	rm -f $OOINSTDIR/basis$VERSION/program/$dll.config
+	rm -f $OOINSTDIR/$dll_name.dll
+	rm -f $OOINSTDIR/$dll_name.dll.config
+	rm -f $OOINSTDIR/$dll_name.config
 
 	# remove the deleted fixes from the filelist
 	if test -n "$OODESTDIR" ; then
-	    file_list=`grep "^$OOINSTBASE/$dll$" $OODESTDIR/gid* | head -n 1 | cut -d: -f1`
-	    test -z "$file_list" && echo "Error: \"$OOINSTBASE/$dll\" has not found in any filelist" && exit 1;
-	    sed -e "s|^$OOINSTBASE/basis$VERSION/$dll$||" \
-	        -e "s|^$OOINSTBASE/basis$VERSION/$dll.config$||" \
+	    file_list=`grep "^$OOINSTBASE/$dll_name.dll$" $OODESTDIR/gid* | head -n 1 | cut -d: -f1`
+	    test -z "$file_list" && echo "Error: \"$OOINSTBASE/$dll_name.dll\" has not found in any filelist" && exit 1;
+	    sed -e "s|^$OOINSTBASE/$dll_name.dll$||" \
+		-e "s|^$OOINSTBASE/$dll_name.dll.config$||" \
+	        -e "s|^$OOINSTBASE/$dll_name.config$||" \
 		$file_list >$file_list.mono
 	    mv $file_list.mono $file_list
 	fi
