Extend the switch --with-icons to accept more icons sets
* configure.in: extend the switch --with-icons to accept more icons sets
* download.in, bin/build-ooo, bin/install-artwork, bin/package-ooo,
bin/setup.in, bin/unpack: add support for more icons sets;
the place where to download icons is in download.in where it
belongs
* Makefile.shared, bin/unpack-icons, save-resources: removed the
obsolete targets save.resources, rebuild.resources and related
helper tools

* patches/OOO_1_1/scp-no-ooo-res.diff, patches/OOO_1_1_2/apply
(SuSEOnly, NLDOnly): remove the unused ooo-res after it is copied
to the really used iso-res by gid_Procedure_Copy_Iso_Res

* build-wizard-bitmap-scp.diff: to SuSEOnly, NLDOnly,
* print-type42.diff: to SuSEOnly, NLDOnly, PLDOnly

* bin/package-lang: set $Target and $Id from the related environment
variables set by bin/setup; install correctly ooo-res as the really
used iso-res

diff --git a/bin/install-artwork b/bin/install-artwork
--- a/bin/install-artwork
+++ b/bin/install-artwork
@@ -23,7 +23,11 @@ else
 fi
 
 echo "Copying icons into the tree"
-cp -Rf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
+if test "z$OOO_ICONS_VER_TO_INSTALL" = "z" ; then
+    # defaults to the first icons set
+    OOO_ICONS_VER_TO_INSTALL=${OOO_ICONS_VERS%% *}
+fi
+cp -Rf $BUILDDIR/$OOO_ICONS_VER_TO_INSTALL/* $OOBUILDDIR || echo "Icon copy failed";
 
 cp -vf $TOOLSDIR/fonts/opens___.ttf $OOBUILDDIR/extras/source/truetype/symbol || echo "font copy failed";
 echo "Copied new opensymbol font into the tree";
diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -45,8 +45,9 @@ if test "z$ENABLE_JAVA" = "zyes" &&
     check_tarball $JDK_TARBALL
 fi
 check_tarball $OOO_TARBALL
-check_tarball $OOO_ICONS_TARBALL
-
+for ooo_icons_tarball in $OOO_ICONS_TARBALLS ; do
+    check_tarball $ooo_icons_tarball
+done
 if test "z$BUILD_WIN32" != "z"; then
     check_tarball $OOO_SCALED_ICONS_TARBALL
 fi
@@ -85,7 +86,9 @@ if test "z$SYSTEM_GCC" = "z"; then
 fi
 
 echo "Unpacking icons"
-tar $OOO_ICONS_UNTAR_OPTIONS $SRCDIR/$OOO_ICONS_TARBALL || exit 1;
+for ooo_icons_tarball in $OOO_ICONS_TARBALLS ; do
+    tar $OOO_ICONS_UNTAR_OPTIONS $SRCDIR/$ooo_icons_tarball || exit 1;
+done
 
 if test "z$BUILD_WIN32" != "z"; then
     echo "Unpacking scaled icons"
@@ -161,9 +164,16 @@ if test "z$SYSTEM_GCC" = "z"; then
     fi
     
     if test ! -d "$BUILDDIR/$GCC_VER" ||
-	test ! -d "$BUILDDIR/$OOO_ICONS_VER" ||
 	test ! -d "$BUILDDIR/$BINUTILS_VER"; then
         echo "Missing some of the helper source";
         exit 1;
     fi
+    
+    for ooo_icons_ver in $OOO_ICONS_VERS ; do
+	if test ! -d "$BUILDDIR/$ooo_icons_ver" ; then
+    	    echo "Missing extra icons";
+	    exit 1;
+	fi
+    done
+
 fi
