Bin backup files.
* Warning *
* Large changes underway branch temporarily unstable *

* patches/apply.pl (apply_patches): bin backup files.

* patches/OOO_1_1/gui-splash-redraw.diff: re-hash for
VCL plug salbmp.cxx

* bin/install-artwork: bin -v on icon install / copy.

* patches/vclplug/vcl-util.diff: add KDE plug linking.

* configure.in, bin/setup.in: hack out WIDGET_SETS, in
favour of --enable-kde / --enable-gtk, OOO_WIDGET_FLAGS

diff --git a/bin/install-artwork b/bin/install-artwork
--- a/bin/install-artwork
+++ b/bin/install-artwork
@@ -22,7 +22,8 @@ else
     echo "Copied Win32 bug-work into the tree";
 fi
 
-cp -Rvf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
+echo "Copying icons into the tree"
+cp -Rf $BUILDDIR/$OOO_ICONS_VER/* $OOBUILDDIR || echo "Icon copy failed";
 
 cp -vf $TOOLSDIR/fonts/opens___.ttf $OOBUILDDIR/extras/source/truetype/symbol || echo "font copy failed";
 echo "Copied new opensymbol font into the tree";
