Back-port fix.
* patches/src680-snap-2004-10-05/apply,
* patches/src680/gtk-dep.diff: back-port fix.

* bin/setup.in: disable all langs but ENUS.

* patches/src680-snap-2004-10-05/apply: stub.

diff --git a/bin/install-artwork b/bin/install-artwork
--- a/bin/install-artwork
+++ b/bin/install-artwork
@@ -11,9 +11,10 @@ cp $TOOLSDIR/src/openabout_*.bmp $OOBUILDDIR/offmgr/res/
 cp $TOOLSDIR/src/openintro_*.bmp $OOBUILDDIR/offmgr/res/
 
 if test "z$BUILD_WIN32" = "z"; then
-    echo "Installing / scaling icons";
-    $TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
-    echo "done icon scaling";
+     echo "Not scaling icons"
+#    echo "Installing / scaling icons";
+#    $TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
+#    echo "done icon scaling";
 else
     echo "Copying scaled icons in please wait ..."
     cp -Rf $BUILDDIR/$OOO_SCALED_ICONS_VER/* $OOBUILDDIR || echo "Scaled icon copy failed"
@@ -27,7 +28,8 @@ if test "z$OOO_ICONS_VER_TO_INSTALL" = "z" ; then
     # defaults to the first icons set
     OOO_ICONS_VER_TO_INSTALL=${OOO_ICONS_VERS%% *}
 fi
-cp -Rf $BUILDDIR/$OOO_ICONS_VER_TO_INSTALL/* $OOBUILDDIR || echo "Icon copy failed";
+echo "Skip copy"
+# cp -Rf $BUILDDIR/$OOO_ICONS_VER_TO_INSTALL/* $OOBUILDDIR || echo "Icon copy failed";
 
 cp -vf $TOOLSDIR/fonts/opens___.ttf $OOBUILDDIR/extras/source/truetype/symbol || echo "font copy failed";
 echo "Copied new opensymbol font into the tree";
