Search also GAC for the cli_uno_bridge.
* patches/mono/cli_ure-mono-bridge.diff,
scratch/mono-uno-bridge/mono_bridge.cxx: search also GAC for the
cli_uno_bridge.dll, n#357348
* src/cli_cppuhelper.dll.config.in, src/cli_uno_bridge.dll.config.in,
bin/install-mono, configure.in, src/Makefile.am: configure where to
find OOo libraries so that the mono bridge can be  accessed from
anywhere; do not longer need to change the working directory to
<ooo-home>/program
* configure.in, bin/setup.in, bin/package-ooo, bin/install-mono:
add configure switch --with-mono-gac-root; it allows to preinstall
mono GAC even when $DESTDIR is defined; remove the original dlls
when they are installaed into GAC
* test/mono/SpreadsheetSample, test/mono/Makefile: the complex wrapper
SpreadsheetSample is obsolete now

diff --git a/bin/install-mono b/bin/install-mono
--- a/bin/install-mono
+++ b/bin/install-mono
@@ -22,6 +22,10 @@ if ! test -w "$OODESTDIR/" ; then
     exit 0;	   
 fi
 
+# filelist for the GAC stuff
+MONOGACFILELIST=$BUILDDIR/mono_gac
+rm -f $MONOGACFILELIST
+
 # install the pkgconfig file
 # GAC is in /usr/lib even on 64-bit architectures, so the .pc file points to
 # the /usr/lib paths; the .pc file itself must be in the arch dependant path
@@ -29,17 +33,42 @@ fi
 mkdir -p $OODESTDIR${LIBDIRBASE}/pkgconfig/
 cp $SRCDIR/mono-ooo.pc ${OODESTDIR}${LIBDIRBASE}/pkgconfig/mono-$OOOINSTALLDIRNAME.pc
 
+# extra dlls config files
+cp $SRCDIR/cli_cppuhelper.dll.config $OOINSTDIR/program/
+cp $SRCDIR/cli_uno_bridge.dll.config $OOINSTDIR/program/
+
 # install versioned assemblies into the system Global Assembly Cache  (GAC)
 # to  become  part  of  the assemblies that are available for all applications
 # at runtime.
-# Note: It should be done in postinstall script
-#       It cannot be done with DESTDIR defined, definitely
-if test "$RUN_POST_INSTALL_SCRIPTS" = "yes" -a -z "$OODESTDIR" ; then
+if test -z "$OODESTDIR" -o -n "$MONO_GAC_ROOT" ; then
+    test -n "$MONO_GAC_ROOT" && gacutil_root="-root $OODESTDIR$MONO_GAC_ROOT" || gacutil_root=
     for dll in cli_basetypes.dll \
                cli_cppuhelper.dll \
 	       cli_types.dll \
 	       cli_uno_bridge.dll \
 	       cli_ure.dll ; do
-	gacutil -i $OOINSTDIR/program/$dll -package $OOOINSTALLDIRNAME
+	gacutil $gacutil_root -i $OOINSTDIR/program/$dll -package $OOOINSTALLDIRNAME || exit 0
+
+	# the original fixes are not longer needed
+	rm -f $OOINSTDIR/program/$dll
+	rm -f $OOINSTDIR/program/$dll.config
+
+	# remove the deleted fixes from the filelist
+	if test -n "$OODESTDIR" ; then
+	    file_list=`grep "^$OOINSTBASE/program/$dll$" $OODESTDIR/gid* | head -n 1 | cut -d: -f1`
+	    test -z "$file_list" && echo "Error: \"$OOINSTBASE/program/$dll\" has not found in any filelist" && exit 1;
+	    sed "s|^$OOINSTBASE/program/$dll$||" $file_list >$file_list.mono
+	    mv $file_list.mono $file_list
+	fi
     done
+
+    # filelist for the GAC
+    if test -n "$OODESTDIR" ; then
+        for dir in `find $OODESTDIR/usr/lib/mono -type d -regex ".*/cli_[_a-z]*" -o -regex ".*/ooo-2.0"` ; do
+	    find $dir -type d | sed "s|^$OODESTDIR\(.*\)|%dir \1|" >>$MONOGACFILELIST
+	    find $dir -type f -o -type l | sed "s|^$OODESTDIR\(.*\)|\1|" >>$MONOGACFILELIST
+	done
+	sort $MONOGACFILELIST >$MONOGACFILELIST.mono
+	mv $MONOGACFILELIST.mono $MONOGACFILELIST
+    fi
 fi
