Added some more debug thanks to Ken Foskey.
* bin/build-ooo: added some more debug thanks
to Ken Foskey.

diff --git a/bin/install-artwork b/bin/install-artwork
--- a/bin/install-artwork
+++ b/bin/install-artwork
@@ -15,9 +15,10 @@ if test "z$BUILD_WIN32" = "z"; then
     $TOOLSDIR/bin/scale-icons $OOBUILDDIR || echo "Error: scaling failed";
     echo "done icon scaling";
 else
-    cp -Rvf $BUILDDIR/$OOO_SCALED_ICONS_VER/* $OOBUILDDIR || echo "Scaled icon copy failed"
-    cp -vf $TOOLSDIR/src/file-bug-16.bmp $OOBUILDDIR/res/sc05406.bmp
-    cp -vf $TOOLSDIR/src/file-bug-24.bmp $OOBUILDDIR/res/lc05406.bmp
+    echo "Copying scaled icons in please wait ..."
+    cp -Rf $BUILDDIR/$OOO_SCALED_ICONS_VER/* $OOBUILDDIR || echo "Scaled icon copy failed"
+    cp -f $TOOLSDIR/src/file-bug-16.bmp $OOBUILDDIR/res/sc05406.bmp
+    cp -f $TOOLSDIR/src/file-bug-24.bmp $OOBUILDDIR/res/lc05406.bmp
     echo "Copied Win32 bug-work into the tree";
 fi
 
