Build with debug info
* test/mono/Makefile: build with debug info

* bin/install-mono: updated file locations for 3.x install

diff --git a/bin/install-mono b/bin/install-mono
--- a/bin/install-mono
+++ b/bin/install-mono
@@ -52,13 +52,13 @@ done
 # at runtime.
 if test -z "$OODESTDIR" -o -n "$MONO_GAC_ROOT" ; then
     test -n "$MONO_GAC_ROOT" && gacutil_root="-root $OODESTDIR$MONO_GAC_ROOT" || gacutil_root=
-    for dll in cli_basetypes.dll \
-               cli_cppuhelper.dll \
-	       cli_uretypes.dll \
-	       cli_oootypes.dll \
-	       cli_uno_bridge.dll \
-	       cli_ure.dll ; do
-	gacutil $gacutil_root -i $OOINSTDIR/program/$dll -package $OOOINSTALLDIRNAME || exit 0
+    for dll in ure/lib/cli_basetypes.dll \
+               ure/lib/cli_cppuhelper.dll \
+	       ure/lib/cli_uretypes.dll \
+	       basis-link/program/cli_oootypes.dll \
+	       ure/lib/cli_uno_bridge.dll \
+	       ure/lib/cli_ure.dll ; do
+	gacutil $gacutil_root -i $OOINSTDIR/$dll -package $OOOINSTALLDIRNAME || exit 0
 
 	# the original fixes are not longer needed
 	rm -f $OOINSTDIR/basis3.0/program/$dll
@@ -66,10 +66,10 @@ if test -z "$OODESTDIR" -o -n "$MONO_GAC_ROOT" ; then
 
 	# remove the deleted fixes from the filelist
 	if test -n "$OODESTDIR" ; then
-	    file_list=`grep "^$OOINSTBASE/program/$dll$" $OODESTDIR/gid* | head -n 1 | cut -d: -f1`
-	    test -z "$file_list" && echo "Error: \"$OOINSTBASE/program/$dll\" has not found in any filelist" && exit 1;
-	    sed -e "s|^$OOINSTBASE/basis3.0/program/$dll$||" \
-	        -e "s|^$OOINSTBASE/basis3.0/program/$dll.config$||" \
+	    file_list=`grep "^$OOINSTBASE/$dll$" $OODESTDIR/gid* | head -n 1 | cut -d: -f1`
+	    test -z "$file_list" && echo "Error: \"$OOINSTBASE/$dll\" has not found in any filelist" && exit 1;
+	    sed -e "s|^$OOINSTBASE/basis3.0/$dll$||" \
+	        -e "s|^$OOINSTBASE/basis3.0/$dll.config$||" \
 		$file_list >$file_list.mono
 	    mv $file_list.mono $file_list
 	fi
@@ -77,7 +77,7 @@ if test -z "$OODESTDIR" -o -n "$MONO_GAC_ROOT" ; then
 
     # filelist for the GAC
     if test -n "$OODESTDIR" ; then
-        for dir in `find $OODESTDIR/usr/lib/mono -type d -regex ".*/cli_[_a-z]*" -o -regex ".*/ooo-2.0"` ; do
+        for dir in `find $OODESTDIR/usr/lib/mono -type d -regex ".*/cli_[_a-z]*" -o -regex ".*/ooo-3.0"` ; do
 	    find $dir -type d | sed "s|^$OODESTDIR\(.*\)|%dir \1|" >>$MONOGACFILELIST
 	    find $dir -type f -o -type l | sed "s|^$OODESTDIR\(.*\)|\1|" >>$MONOGACFILELIST
 	done
