Use download.
* bin/make-win32-iso: Use download.list instead of hardcoding the
list here. Don't put the non-redistributable files in the source
ISO, though.

diff --git a/bin/make-win32-iso b/bin/make-win32-iso
--- a/bin/make-win32-iso
+++ b/bin/make-win32-iso
@@ -125,17 +125,21 @@ mkisofs -quiet -J -r -V OOO-$OOO_PACKAGEVERSION-$COUNTER -o $OUTDIR/OOo-$OOO_PAC
 
 cd $TOOLSDIR
 make distdir >/dev/null
-cp -p src/$CVSTAG-*.tar.bz2 $SRCISOROOT/src
-cp -p src/apache-ant-1.6.5-bin.tar.gz $SRCISOROOT/src
-cp -p src/$BUILD_MOZILLA_SOURCE $SRCISOROOT/src
-cp -p src/glib-1.2.10.tar.gz $SRCISOROOT/src
-cp -p src/libIDL-0.6.8.tar.gz $SRCISOROOT/src
-cp -p src/wintools.zip $SRCISOROOT/src
-cp -p src/$MDBTOOLS_SRC $SRCISOROOT/src
-cp -p src/$OOO_EXTRA_ARTWORK $SRCISOROOT/src
-cp -p src/xt-20051206-src-only.zip $SRCISOROOT/src
-cp -p src/biblio.tar.bz2 $SRCISOROOT/src
-cp -p src/lp_solve_5.5.tar.gz $SRCISOROOT/src
+if [ -f download.list ]; then
+    while read FILENAME; do
+	case "$FILENAME" in
+	*.exe)
+	    # Ignore presumably non-redistributable files
+	    ;;
+	*)
+	    cp -p src/$FILENAME $SRCISOROOT/src
+	    ;;
+	esac
+    done <download.list
+else
+    echo "Missing download.list, did you remove it?"
+    exit 1
+fi
 
 cd $SRCISOROOT
 
