Re-write in perl.
* bin/ooconfig: re-write in perl.

diff --git a/bin/ooconfig b/bin/ooconfig
--- a/bin/ooconfig
+++ b/bin/ooconfig
@@ -1,362 +1,183 @@
-#!/bin/sh
+#!/usr/bin/perl -w
 
-help()
+use strict;
+
+# mangling to names:
+#   bool: enable-$/disable-$, int,string: set-$
+
+# setting name	-> [ '/path/to/key',
+#                    'bool|string|int|enum,a,b,c|custom',
+#                    '<help-description>',
+#                    &custom_func ]
+my $path_idx = 0;
+my $type_idx = 1;
+my $help_idx = 2;
+my $func_idx = 2;
+
+my $settings = {
+    'enable-accessibility' => [ '/desktop/gnome/interface/accessibility', 'bool' ],
+    'enable-auto-save'     => [ '/apps/openoffice/auto_save', 'bool' ],
+    'enable-create-backup' => [ '/apps/openoffice/create_backup', 'bool' ],
+    'enable-font-anti-aliasing' => [ '/apps/openoffice/use_font_anti_aliasing', 'bool' ],
+    'enable-font-history' => [ '/apps/openoffice/show_font_history', 'bool' ],
+    'enable-font-preview' => [ '/apps/openoffice/show_font_preview', 'bool' ],
+    'enable-menu-icons' => [ '/apps/openoffice/show_menu_icons', 'bool' ],
+    'enable-menu-inactive-items' => [ '/apps/openoffice/show_menu_inactive_items', 'bool' ],
+    'enable-opengl' => [ '/apps/openoffice/use_opengl', 'bool' ],
+    'enable-optimize-opengl' => [ '/apps/openoffice/optimize_opengl', 'bool' ],
+    'enable-printing' => [ '/desktop/gnome/lockdown/disable_printing', 'bool' ],
+    'enable-printing-modifies-doc' => [ '/apps/openoffice/printing_modifies_doc', 'bool' ],
+    'enable-recommend-password-on-save' => [ '/apps/openoffice/lockdown/recommend_password_on_save', 'bool' ],
+    'enable-remove-personal-info-on-save' => [ '/apps/openoffice/lockdown/remove_personal_info_on_save', 'bool' ],
+    'enable-system-file-dialog' => [  '/apps/openoffice/use_system_file_dialog', 'bool' ],
+    'enable-system-font' => [  '/apps/openoffice/use_system_font', 'bool' ],
+    'enable-ui-customization' => [ '/apps/openoffice/lockdown/disable_ui_customization', 'bool' ],
+    'enable-warn-alien-format' => [ '/apps/openoffice/warn_alien_format', 'bool' ],
+    'enable-warn-info-create-pdf' => [ '/apps/openoffice/lockdown/warn_info_create_pdf', 'bool' ],
+    'enable-warn-info-printing' => [ '/apps/openoffice/lockdown/warn_info_printing', 'bool' ],
+    'enable-warn-info-signing' => [ '/apps/openoffice/lockdown/warn_info_signing', 'bool' ],
+    'enable-warn-info-saving' => [ '/apps/openoffice/lockdown/warn_info_saving', 'bool' ],
+    'set-auto-save-interval' => [ '/apps/openoffice/auto_save_interval', 'int' ],
+    'set-font-anti-aliasing-min-pixel' => [  '/apps/openoffice/font_anti_aliasing_min_pixel', 'int' ],
+    'set-icon-size' => [ '/apps/openoffice/icon_size', 'enum,small,large,auto' ],
+    'set-macro-security-level' => [ '/apps/openoffice/lockdown/macro_security_level', 'enum,low,medium,high,veryhigh' ],
+    'set-mailer-program' => [ '/desktop/gnome/url-handlers/mailto/command', 'string' ],
+    'set-proxy-mode' => [ '/system/proxy/mode', 'enum,none,manual,auto' ],
+    'set-proxy-http-host' => [ '/system/http_proxy/host', 'string' ],
+    'set-proxy-http-port' => [ '/system/http_proxy/port', 'int' ],
+    'set-proxy-ftp-host' => [ '/system/proxy/ftp_host', 'string' ],
+    'set-proxy-ftp-port' => [ '/system/proxy/ftp_port', 'int' ],
+    'set-undo-steps' => [ '/apps/openoffice/undo_steps', 'int' ],
+    'set-writer-default-document' => [ '/apps/openoffice/writer_default_document_format', 'custom', , \&parse_writer ],
+    'set-calc-default-document' => [ '/apps/openoffice/calc_default_document_format', 'custom' , , \&parse_calc ],
+    'set-impress-default-document' => [ '/apps/openoffice/impress_default_document_format', 'custom', , \&parse_impress ]
+};
+
+sub validate_enum($$$)
 {
-	cat<<EOF
-Usage: `basename $0` setting=value
-where setting is one of:
-	--enable-accessibility
-	--enable-auto-save
-	--enable-create-backup
-	--enable-font-anti-aliasing
-	--enable-font-history
-	--enable-font-preview
-	--enable-menu-icons
-	--enable-menu-inactive-items
-	--enable-opengl
-	--enable-optimize-opengl
-	--enable-printing
-	--enable-printing-modifies-doc
-	--enable-recommend-password-on-save
-	--enable-remove-personal-info-on-save
-	--enable-system-file-dialog
-	--enable-system-font
-	--enable-ui-customization
-	--enable-warn-alien-format
-	--enable-warn-info-create-pdf
-	--enable-warn-info-printing
-	--enable-warn-info-signing
-	--enable-warn-info-saving
-	--set-auto-save-interval
-	--set-calc-default-document
-	--set-font-anti-aliasing-min-pixel
-	--set-icon-size
-	--set-impress-default-document
-	--set-macro-security-level
-	--set-mailer-program
-	--set-proxy-mode
-	--set-proxy-http-host
-	--set-proxy-http-port
-	--set-proxy-ftp-host
-	--set-proxy-ftp-port
-	--set-undo-steps
-	--set-writer-default-document
-EOF
+    my ($opts, $value, $key) = @_;
+
+    my @enum_opts = split (/,/, $opts);
+    my $hit = 0;
+    for my $val (@enum_opts) {
+	$hit = 1 if ($val eq $value);
+    }
+    if (!$hit) {
+	print STDERR "Error: supported values of $key are $opts: $value is invalid\n";
+	exit 1;
+    }
 }
 
-isdigit()
+sub parse_writer($$$)
 {
-	case $1 in
-
-		*[!0-9]*)
-			return 1 ;;
-
-		*)
-			return 0 ;;
-
-	esac
+    my ($attrs, $key, $value) = @_;
+    validate_enum ("odt,doc,sxw", $value, $key);
+    return "writer8" if ($value eq 'odt');
+    return "MS Word 97" if ($value eq 'doc');
+    return "StarOffice XML (Writer)" if ($value eq 'sxw');
+    die "impossible";
 }
 
-validate_and_translate()
+sub parse_calc($$$)
 {
-	if [ -z "$1" -o -z "$2" ] ; then
-		help
-		exit 1
-	fi
-
-	case "$1" in
-
-		--enable-printing						| \
-		--enable-ui-customization)
-
-			if [ "$2" == "yes" ] ; then
-				value=0
-			elif [ "$2" == "no" ] ; then
-				value=1
-			else
-				echo "Supported values for $1 are 'yes' or 'no'"
-				exit 1
-			fi ;;
-
-		--enable-accessibility					| \
-		--enable-auto-save						| \
-		--enable-create-backup					| \
-		--enable-font-anti-aliasing				| \
-		--enable-font-history					| \
-		--enable-font-preview					| \
-		--enable-menu-icons						| \
-		--enable-menu-inactive-items			| \
-		--enable-opengl							| \
-		--enable-optimize-opengl				| \
-		--enable-printing-modifies-doc			| \
-		--enable-recommend-password-on-save		| \
-		--enable-remove-personal-info-on-save	| \
-		--enable-system-file-dialog				| \
-		--enable-system-font					| \
-		--enable-warn-alien-format				| \
-		--enable-warn-info-create-pdf			| \
-		--enable-warn-info-printing				| \
-		--enable-warn-info-signing				| \
-		--enable-warn-info-saving)
-
-			if [ "$2" == "yes" ] ; then
-				value=1
-			elif [ "$2" == "no" ] ; then
-				value=0
-			else
-				echo "Supported values for $1 are 'yes' or 'no'"
-				exit 1
-			fi ;;
-
-		--set-auto-save-interval)
-
-			if ! isdigit "$2" -o [ "$2" -lt 1 -o "$2" -gt 60 ] ; then
-				echo "Supported values for $1 are integers from 1 through 60"
-				exit 1
-			else
-				value=$2
-			fi ;;
-
-		--set-font-anti-aliasing-min-pixel | \
-		--set-undo-steps)
-
-			if ! isdigit "$2" -o [ "$2" -lt 1 ] ; then
-				echo "Supported values for $1 are integers greater than 1"
-				exit 1
-			else
-				value=$2
-			fi ;;
-
-		--set-icon-size)
-
-			if [ "$2" == "small" ] ; then
-				value=0
-			elif [ "$2" == "large" ] ; then
-				value=1
-			elif [ "$2" == "auto" ] ; then
-				value=2
-			else
-				echo "Supported values for $1 are 'small', 'large' and 'auto'"
-				exit 1
-			fi ;;
-
-		--set-macro-security-level)
-
-			if [ "$2" == "low" ] ; then
-				value=0
-			elif [ "$2" == "medium" ]; then
-				value=1
-			elif [ "$2" == "high" ] ; then
-				value=2
-			elif [ "$2" == "veryhigh" ] ; then
-				value=3
-			else
-				echo "Supported values for $1 are 'low', 'medium', 'high' and 'veryhigh'"
-				exit 1
-			fi ;;
-
-		--set-proxy-mode)
-
-			if [ "$2" != "none" -a "$2" != "manual" -a "$2" != "auto" ] ; then
-				echo "Supported values for $1 are 'none', 'manual' and 'auto'"
-				exit 1
-			else
-				value=$2
-			fi ;;
-
-		--set-proxy-http-port			| \
-		--set-proxy-ftp-port)
-
-			if ! isdigit "$2" -o "$2" -lt 0 ] ; then
-				echo "Supported values for $1 are positive integers"
-				exit 1
-			else
-				value=$2
-			fi ;;
-
-		--set-mailer-program			| \
-		--set-proxy-mode				| \
-		--set-proxy-http-host			| \
-		--set-proxy-ftp-host)
-
-			echo "Use with care. No validation done."
-			value="$2" ;;
-
-		--set-calc-default-document)
-
-			if [ "$2" == "ods" ] ; then
-				value="calc8"
-			elif [ "$2" == "xls" ]; then
-				value="MS Excel 97"
-			elif [ "$2" == "sxc" ] ; then
-				value="StarOffice XML (Calc)"
-			else
-				echo "Supported values for $1 are 'ods', 'xls' and 'sxc'"
-				exit 1
-			fi ;;
-
-		--set-impress-default-document)
-
-			if [ "$2" == "odp" ] ; then
-				value="impress8"
-			elif [ "$2" == "ppt" ]; then
-				value="MS PowerPoint 97"
-			elif [ "$2" == "sxi" ] ; then
-				value="StarOffice XML (Impress)"
-			else
-				echo "Supported values for $1 are 'odp', 'ppt' and 'sxi'"
-				exit 1
-			fi ;;
-
-		--set-writer-default-document)
-
-			if [ "$2" == "odt" ] ; then
-				value="writer8"
-			elif [ "$2" == "doc" ]; then
-				value="MS Word 97"
-			elif [ "$2" == "sxw" ] ; then
-				value="StarOffice XML (Writer)"
-			else
-				echo "Supported values for $1 are 'odt', 'doc' and 'sxw'"
-				exit 1
-			fi ;;
-
-		*)
-			help
-			exit 1 ;;
-
-	esac
+    my ($attrs, $key, $value) = @_;
+    validate_enum ("ods,xls,sxc", $value, $key);
+    return "calc8" if ($value eq 'ods');
+    return "MS Excel 97" if ($value eq 'xls');
+    return "StarOffice XML (Calc)" if ($value eq 'sxc');
+    die "impossible";
 }
 
-
-main()
+sub parse_impress($$$)
 {
-	echo "$@" | grep -q =
-	if [ $? -ne 0 -o $# -ne 1 ] ; then
-		help
-		exit 1
-	fi
+    my ($attrs, $key, $value) = @_;
+    validate_enum ("odp,ppt,sxi", $value, $key);
 
-	setting=`echo $1 | awk -F= '{print $1}'`
-	input_value=`echo $1 | awk -F= '{print $2}'`
-
-	validate_and_translate "$setting" "$input_value"
-
-	case "$setting" in
-
-		--enable-accessibility)
-			gconftool-2 --set "/desktop/gnome/interface/accessibility" --type bool "$value" ;;
-
-		--enable-auto-save)
-			gconftool-2 --set "/apps/openoffice/auto_save" --type bool "$value" ;;
-
-		--enable-create-backup)
-			gconftool-2 --set "/apps/openoffice/create_backup" --type bool "$value" ;;
-
-		--enable-font-anti-aliasing)
-			gconftool-2 --set "/apps/openoffice/use_font_anti_aliasing" --type bool "$value" ;;
-
-		--enable-font-history)
-			gconftool-2 --set "/apps/openoffice/show_font_history" --type bool "$value" ;;
-
-		--enable-font-preview)
-			gconftool-2 --set "/apps/openoffice/show_font_preview" --type bool "$value" ;;
-
-		--enable-menu-icons)
-			gconftool-2 --set "/apps/openoffice/show_menu_icons" --type bool "$value" ;;
-
-		--enable-menu-inactive-items)
-			gconftool-2 --set "/apps/openoffice/show_menu_inactive_items" --type bool "$value" ;;
-
-		--enable-opengl)
-			gconftool-2 --set "/apps/openoffice/use_opengl" --type bool "$value" ;;
-
-		--enable-optimize-opengl)
-			gconftool-2 --set "/apps/openoffice/optimize_opengl" --type bool "$value" ;;
-
-		--enable-printing)
-			gconftool-2 --set "/desktop/gnome/lockdown/disable_printing" --type bool "$value" ;;
-
-		--enable-printing-modifies-doc)
-			gconftool-2 --set "/apps/openoffice/printing_modifies_doc" --type bool "$value" ;;
-
-		--enable-recommend-password-on-save)
-			gconftool-2 --set "/apps/openoffice/lockdown/recommend_password_on_save" --type bool "$value" ;;
-
-		--enable-remove-personal-info-on-save)
-			gconftool-2 --set "/apps/openoffice/lockdown/remove_personal_info_on_save" --type bool "$value" ;;
-
-		--enable-system-file-dialog)
-			gconftool-2 --set "/apps/openoffice/use_system_file_dialog" --type bool "$value" ;;
-
-		--enable-system-font)
-			gconftool-2 --set "/apps/openoffice/use_system_font" --type bool "$value" ;;
-
-		--enable-ui-customization)
-			gconftool-2 --set "/apps/openoffice/lockdown/disable_ui_customization" --type bool "$value" ;;
-
-		--enable-warn-alien-format)
-			gconftool-2 --set "/apps/openoffice/warn_alien_format" --type bool "$value" ;;
-
-		--enable-warn-info-create-pdf)
-			gconftool-2 --set "/apps/openoffice/lockdown/warn_info_create_pdf" --type bool "$value" ;;
-
-		--enable-warn-info-printing)
-			gconftool-2 --set "/apps/openoffice/lockdown/warn_info_printing" --type bool "$value" ;;
-
-		--enable-warn-info-signing)
-			gconftool-2 --set "/apps/openoffice/lockdown/warn_info_signing" --type bool "$value" ;;
-
-		--enable-warn-info-saving)
-			gconftool-2 --set "/apps/openoffice/lockdown/warn_info_saving" --type bool "$value" ;;
-
-		--set-auto-save-interval)
-			gconftool-2 --set "/apps/openoffice/auto_save_interval" --type int "$value" ;;
-
-		--set-calc-default-document)
-			gconftool-2 --set "/apps/openoffice/calc_default_document_format" --type string "$value" ;;
-
-		--set-font-anti-aliasing-min-pixel)
-			gconftool-2 --set "/apps/openoffice/font_anti_aliasing_min_pixel" --type int "$value" ;;
-
-		--set-icon-size)
-			gconftool-2 --set "/apps/openoffice/icon_size" --type int "$value" ;;
-
-		--set-impress-default-document)
-			gconftool-2 --set "/apps/openoffice/impress_default_document_format" --type string "$value" ;;
-
-		--set-macro-security-level)
-			gconftool-2 --set "/apps/openoffice/lockdown/macro_security_level" --type int "$value" ;;
-
-		--set-mailer-program)
-			gconftool-2 --set "/desktop/gnome/url-handlers/mailto/command" --type string "$value %s" ;;
-
-		--set-proxy-mode)
-			gconftool-2 --set "/system/proxy/mode" --type string "$value" ;;
-
-		--set-proxy-http-host)
-			gconftool-2 --set "/system/http_proxy/host" --type string "$value" ;;
-
-		--set-proxy-http-port)
-			gconftool-2 --set "/system/http_proxy/port" --type int "$value" ;;
-
-		--set-proxy-ftp-host)
-			gconftool-2 --set "/system/proxy/ftp_host" --type string "$value" ;;
-
-		--set-proxy-ftp-port)
-			gconftool-2 --set "/system/proxy/ftp_port" --type int "$value" ;;
-
-		--set-undo-steps)
-			gconftool-2 --set "/apps/openoffice/undo_steps" --type int "$value" ;;
-
-		--set-writer-default-document)
-			gconftool-2 --set "/apps/openoffice/writer_default_document_format" --type string "$value" ;;
-
-		*)
-			help ;;
-	esac
-
+    return "impress8" if ($value eq 'odp');
+    return "MS PowerPoint 97" if ($value eq 'ppt');
+    return "StarOffice XML (Impress)" if ($value eq 'sxi');
+    die "impossible";
 }
 
+sub help()
+{
+    print "Usage: ooadmin --setting=value\n  where setting is one of:\n";
+    for my $key (keys %{$settings}) {
+	my $attrs = $settings->{$key};
+	my $help = $attrs->[$help_idx];
+	print "\t--" . $key;
+	print " : $help" if (defined $help);
+	print "\n";
+    }
+}
 
-main "$@"
+sub conf_type($)
+{
+    my $type = shift;
+    $type = 'string' if ($type =~ m/^enum,/);
+    return $type;
+}
+
+sub set_key($$)
+{
+    my ($attrs, $conf_value) = @_;
+    my $sys_str = "gconftool-2" .
+	"--set '" . $attrs->[$path_idx] . "' " .
+	"--type " . conf_type ($attrs->[$type_idx]) . " " .
+	$conf_value;
+#    print "\$ $sys_str\n";
+    `$sys_str` || die "Set failed: $!";
+}
+
+for my $arg (@ARGV) {
+    if ($arg =~ m/^--help/ || $arg =~ m/^-h/) {
+	help();
+	exit 0;
+    }
+    if (!($arg =~ m/^--(.*)=(.*)/)) {
+	print STDERR "Error: syntax --enable-foo=yes\n";
+	exit 1;
+    }
+    if (!defined $settings->{$1}) {
+	print STDERR "Unknown setting '$arg'\n";
+	exit 1;
+    }
+}
+
+for my $arg (@ARGV) {
+    $arg =~ m/^--(.*)=(.*)/;
+    my $key = $1;
+    my $value = $2;
+    my $attrs = $settings->{$key};
+    my $path  = $attrs->[$path_idx];
+    my $type  = $attrs->[$type_idx];
+
+#    print "Key '$key' value '$value' '$arg' $attrs, $path, $type\n";
+    my $conf_value;
+
+    if ($type eq 'bool') {
+	if ($value =~ m/^yes$/g ||
+	    $value =~ m/^true$/g) {
+	    $conf_value = 1;
+	} else {
+	    $conf_value = 0;
+	}
+
+    } elsif ($type eq 'int' ||
+	     $type eq 'string') {
+	$conf_value = $value;
+
+    } elsif ($type =~ m/^enum,(.*)$/) {
+	validate_enum ($1, $value, $key);
+	$conf_value = $value;
+
+    } elsif ($type eq 'custom') {
+	my $function = $attrs->[$func_idx];
+	$conf_value = $function->($attrs, $key, $value);
+
+    } else {
+	print STDERR "Error in type '$type' on key '$key'\n";
+	exit 1;
+    }
+    set_key ($attrs, $conf_value);
+}
