Use the English source if it is not yet localized; it helps to install for example Japanese, where the wordbook is not localized yet.
* bin/ooinstall: use the English source if it is not yet localized;
it helps to install for example Japanese, where the wordbook is not
localized yet.

* bin/install-help, bin/package-ooo, bin/setup.in: fix support
to install help from external helpcontent using the variable
WITH_LANG (FIXME: It does not suport the setting ALL);
create symlink to the English help instead of to duplicate it

* bin/build-ooo: last missing update LANGS (setup) -> WITH_LANG
(configure)

diff --git a/bin/package-ooo b/bin/package-ooo
--- a/bin/package-ooo
+++ b/bin/package-ooo
@@ -203,8 +203,31 @@ $TOOLSDIR/bin/install-dictionaries || exit 1;
 
 # Java-disabled builds do not create help
 if test -d $OOINSTDIR/help; then
-  echo "Installing localized help contents..."
-  $TOOLSDIR/bin/install-help || exit 1
+    echo "Removing dupplicated English help"
+  
+    for lang in $WITH_LANG ; do
+	test "$lang" = "en-US" && continue;
+	test ! -f $OOINSTDIR/help/en/sbasic.cfg -o ! -f $OOINSTDIR/help/$lang/sbasic.cfg && continue;
+	if diff $OOINSTDIR/help/en/sbasic.cfg $OOINSTDIR/help/$lang/sbasic.cfg >/dev/null 2>&1 ; then
+	    echo "... remove $lang"
+	    rm -rf $OOINSTDIR/help/$lang
+	    grep -v "$OOINSTBASE/help/$lang" $OODESTDIR/gid_Module_Root.$lang >$OODESTDIR/gid_Module_Root.$lang.new
+	    mv -f $OODESTDIR/gid_Module_Root.$lang.new $OODESTDIR/gid_Module_Root.$lang
+	fi
+    done
+
+    echo "Installing localized help contents..."
+    $TOOLSDIR/bin/install-help || exit 1
+    
+    echo "Adding missing links to the English help"
+    for lang in $WITH_LANG ; do
+	test "$lang" = "en-US" && continue;
+	if test -d $OOINSTDIR/help/en -a ! -d $OOINSTDIR/help/$lang ; then
+	    echo "... link $lang"
+	    ln -sf en $OOINSTDIR/help/$lang
+	    echo "$OOINSTBASE/help/$lang" >>$OODESTDIR/gid_Module_Root.$lang
+	fi
+    done
 fi
 
 # move one file from one list of files to a second one
@@ -256,10 +279,11 @@ if test "z$VENDORNAME" != "zDebian" ; then
 		| sort | uniq \
 		> $BUILDDIR/common_list.txt
 	
-	first_skipped=0
-	for lang in $LANGS ; do
-		test "$first_skipped" = "0" && { first_skipped=1; continue; }
-		cp -f gid_Module_Root.$lang $BUILDDIR/lang_${lang}_list.txt
+	for lang in $WITH_LANG ; do
+		lang_lists=
+		test -f gid_Module_Root.$lang           && lang_lists="gid_Module_Root.$lang"
+		test -f $BUILDDIR/help_${lang}_list.txt && lang_lists="$lang_lists $BUILDDIR/help_${lang}_list.txt"
+		test -n "$lang_lists" && cat $lang_lists >$BUILDDIR/lang_${lang}_list.txt
 	done
 	
 	# sort && uniq suck but eg. gid_Module_Optional_Draw & Impress have substantial overlap
