Rotate sfx2-toolbox-size: remake add lots of FIXMEs to apply, incomplete.
* patches/src680-m62, patches/src680-m63:
buildfix-scp2-system-python,
vcl-toolbox-cleanup: rotate
sfx2-toolbox-size: remake
add lots of FIXMEs to apply, incomplete.

* configure.in, Makefile.am, patches/order etc.: add m63.

* bin/package-ooo: ensure /proc is mounted,
lots more build fixes & desparate hacks to get
a package.

diff --git a/bin/package-ooo b/bin/package-ooo
--- a/bin/package-ooo
+++ b/bin/package-ooo
@@ -178,6 +178,11 @@ cd $OOBUILDDIR/instsetoo_native/util || exit 1;
 BUILD=8825
 INSTALL_PATH=/opt/FFInstall
 
+if ! test -f /proc/meminfo; then
+    echo "The installer cannot work without javaldx running, which requires /proc to be mounted";
+    exit 1;
+fi
+
 export OUT='../unxlngi4.pro'
 export LOCAL_OUT=$OUT
 export LOCAL_COMMON_OUT=$OUT
@@ -195,6 +200,11 @@ echo "Done make_installer.pl work";
 cd $OOINSTDIR/program
 ./pkgchk --shared --quiet
 ./configimport --spool
+
+echo "Cleaning up ...";
+
+# No idea what these files are good for (?)
+rm -Rf $OOINSTDIR/share/uno_packages/cache
 
 echo "Done";
 
@@ -229,7 +239,21 @@ add_used_directories()
 
 echo "Moving package file lists..."
 
+if ! test -f $OODESTDIR/gid_Module_Root; then
+    echo "Failed to generate package file lists";
+    exit 1;
+fi
+
 cd $OODESTDIR
+
+# Nasty hack for now...
+echo "/usr/lib/ooo-1.7/dictionary.lst
+      /usr/lib/ooo-1.7/install-dict
+      /usr/lib/ooo-1.7/program/liblnth680li.so
+      /usr/lib/ooo-1.7/share/registry/modules/data/org/openoffice/Office/Common.xcu
+      /usr/lib/ooo-1.7/share/registry/modules/data/org/openoffice/Office/Scripting.xcu
+      /usr/lib/ooo-1.7/share/registry/modules/data/org/openoffice/Setup.xcu" > gid_Module_Hack
+
 cat gid_Module_Optional_Grfflt \
     gid_Module_Prg_Calc \
     gid_Module_Prg_Math \
@@ -241,7 +265,11 @@ cat gid_Module_Optional_Grfflt \
     gid_Module_Optional_Xsltfiltersamples \
     gid_Module_Prg_Impress \
     gid_Module_Root \
+    gid_Module_Hack \
+    | sort | uniq | \
     > $BUILDDIR/common_list.txt
+
+# sort && uniq suck but eg. gid_Module_Optional_Draw & Impress have substantial overlap
 
 #
 # FIXME: lang-packs etc.
@@ -265,7 +293,7 @@ mv_file_between_flists gnome_list.txt common_list.txt $OOINSTDIR/program/libvclp
 add_used_directories gnome_list.txt common_list.txt
 
 echo "Cleaning up lists of files...";
-rm -f $OODESTDIR/gid_Module_*
+# rm -f $OODESTDIR/gid_Module_*
 
 cd $BUILDDIR
 
