Read list of tests from extra config files; remove the potentially broken user configuration after each test; try to kill the potentially running office with both SIGTERM and even with SIGKILL (just to be sure); print help
* patches/src680/gengal-cleanup.diff, patches/src680/apply:
removes obsolete gengal.rdb and cleans up gengal.sh, i#65361

* bin/test-ooo: read list of tests from extra config files; remove
the potentially broken user configuration after each test; try
to kill the potentially running office with both SIGTERM and
even with SIGKILL (just to be sure); print help
* etc/test.list, etc/test.blacklist: initial lists of tests to be
started for OOo-2.0.3, many thanks to Joerg Skottke
<Joerg.Skottke@sun.com>
* doc/test-ooo.txt: update for the latest changes

* bin/test-ooo-analyze: fix output of two statistics

diff --git a/bin/test-ooo b/bin/test-ooo
--- a/bin/test-ooo
+++ b/bin/test-ooo
@@ -11,228 +11,58 @@
 testToolBin=/usr/lib/ooo-2.0/program/testtool.bin
 
 # where the qatesttool is stored (testcases)
-testToolRoot=/test/OOo/qa
+testToolRoot=/test/OOo/qa/qatesttool
+
+# path to the user configuration directory
+userConfigDir=$HOME/.ooo-2.0
 
 # all tests will be skipped until this script name is found
 # define empty string to do not skip any test
 SKIP_TO_TEST=
-#SKIP_TO_TEST=/qatesttool/writer/loadsave/w_imp_bin.bas
+#SKIP_TO_TEST=writer/loadsave/w_imp_bin.bas
 
-# list of backlisted tests
-# this are temporary blacklisted tests because of a bug in ooo-build
-# It should be empty
-testBlackList=("
-   /qatesttool/framework/extras/extras_fonts.bas\
-   /qatesttool/xml/special/mperform.bas\
-")
+usage()
+{
+    echo "This script sta rt the qatesttool scripts from the given list"
+    echo
+    echo "Usage: ${0##*/} test.list [test.blacklist]"
+    echo
+    echo "	test.list      - list of test scripts to start"
+    echo "	test.blacklist - list of test scripts to skip"
+    echo 
+    echo "	Both files include list of paths to the test scripts, one path"
+    echo "	per line. They can also include comments prefixed by #"
+    echo 
+    echo "Example of the file.list:"
+    echo
+    echo "	# Tests for OOo-2.0.3"
+    echo "	framework/first/first.bas"
+    echo "	framework/first/topten.bas"
+    echo "	framework/level1/f_lvl1_loadsave.bas"
+}
 
-# FIXME: The following list is taken from qatesttool/script/unix/OOoTestRun_unix.sh,
-# we should update it automatically
-# It is necessary because some tests are broken, for example
-# qatesttool/framework/basic/f_basic_protected_libraries.bas. This test even breaks
-# the user configuration, so the other tests are affected as well!!!
+if test -z "$1" -o "$1" = "--help" -o $# -gt 2 ; then
+    usage && exit 1;
+fi
 
-# insert tests here
-testList=("
-   /qatesttool/framework/first/first.bas\
-   /qatesttool/framework/first/topten.bas\
-   /qatesttool/framework/update/f_updt_faxwizard.bas\
-   /qatesttool/framework/update/f_updt_help.bas\
-   /qatesttool/framework/update/f_updt_letterwizard.bas\
-   /qatesttool/framework/update/f_updt_pkgmgr.bas\
-   /qatesttool/framework/update/f_updt_spadmin.bas\
-   /qatesttool/framework/update/f_updt_templates.bas\
-   /qatesttool/framework/update/f_updt_toolbars.bas\
-   /qatesttool/framework/update/f_updt_windowfuncs.bas\
-   /qatesttool/writer/update/w_updt.bas\
-   /qatesttool/math/update/m_updt.bas\
-   /qatesttool/calc/update/c_updt.bas\
-   /qatesttool/chart/update/ch_updt.bas\
-   /qatesttool/graphics/update/i_updt.bas\
-   /qatesttool/graphics/update/gallery.bas\
-   /qatesttool/base/update/b_updt.bas\
-   /qatesttool/base/update/xforms_updt.bas\
-   /qatesttool/xml/update/xm_updt.bas\
-   /qatesttool/writer/update/ww_updt.bas\
-   /qatesttool/writer/update/ma_updt.bas\
-   /qatesttool/graphics/update/d_updt.bas\
-   /qatesttool/framework/basic/check_control_settings_calc.bas\
-   /qatesttool/framework/basic/check_control_settings_graphics.bas\
-   /qatesttool/framework/basic/check_control_settings_writer.bas\
-   /qatesttool/framework/basic/f_basic.bas\
-   /qatesttool/framework/basic/f_basic_modules.bas\
-   /qatesttool/framework/basic/f_scripting_basics.bas\
-   /qatesttool/framework/basic/input/resetregistration.bas\
-   /qatesttool/framework/basic/pbrowser_controls.bas\
-   /qatesttool/framework/basic/pbrowser_events.bas\
-   /qatesttool/framework/extras/extras_autotext.bas\
-   /qatesttool/framework/extras/extras_drawobjects.bas\
-   /qatesttool/framework/extras/extras_labels.bas\
-   /qatesttool/framework/extras/extras_samplefileopen.bas\
-   /qatesttool/framework/extras/extras_sampleopen.bas\
-   /qatesttool/framework/extras/extras_samplepreview.bas\
-   /qatesttool/framework/extras/extras_tableautoformat.bas\
-   /qatesttool/framework/extras/extras_templateedit.bas\
-   /qatesttool/framework/extras/extras_templatefileopen.bas\
-   /qatesttool/framework/extras/extras_templateopen.bas\
-   /qatesttool/framework/extras/extras_templatepreview.bas\
-   /qatesttool/framework/filedlg/filedlg_attributes.bas\
-   /qatesttool/framework/filedlg/filedlg_autocompletion.bas\
-   /qatesttool/framework/filedlg/filedlg_cjkchars.bas\
-   /qatesttool/framework/filedlg/filedlg_dialogtest.bas\
-   /qatesttool/framework/filedlg/filedlg_filenames1.bas\
-   /qatesttool/framework/filedlg/filedlg_filenames2.bas\
-   /qatesttool/framework/filedlg/filedlg_filenames3.bas\
-   /qatesttool/framework/filedlg/filedlg_folders.bas\
-   /qatesttool/framework/filedlg/filedlg_ftpaccess.bas\
-   /qatesttool/framework/filedlg/filedlg_ftpfolders.bas\
-   /qatesttool/framework/filedlg/filedlg_passwords.bas\
-   /qatesttool/framework/first/first.bas\
-   /qatesttool/framework/first/topten.bas\
-   /qatesttool/framework/help/help.bas\
-   /qatesttool/framework/install/install.bas\
-   /qatesttool/framework/install/integration.bas\
-   /qatesttool/framework/level1/f_lvl1_autopilots.bas\
-   /qatesttool/framework/level1/f_lvl1_loadsave.bas\
-   /qatesttool/framework/level1/f_lvl1_ole.bas\
-   /qatesttool/framework/level2/CJK/CJK_CollationDialogue.bas\
-   /qatesttool/framework/level2/CJK/CJK_FeatureSwitch.bas\
-   /qatesttool/framework/level2/CJK/CJK_GridLayout.bas\
-   /qatesttool/framework/level2/CJK/CJK_RubyDialogueProposal.bas\
-   /qatesttool/framework/level2/CJK/NewSortingAlgorithmForJapanese.bas\
-   /qatesttool/framework/level2/benchmarq/f_benchmarq.bas\
-   /qatesttool/framework/level2/slotscfg/slotscfg.bas\
-   /qatesttool/framework/options/f_opt.bas\
-   /qatesttool/framework/options/f_opt_loadsave.bas\
-   /qatesttool/framework/options/f_opt_ooo.bas\
-   /qatesttool/writer/level1/ma_lvl1.bas\
-   /qatesttool/writer/level1/w_CJKCTLDependency.bas\
-   /qatesttool/writer/level1/w_autotext.bas\
-   /qatesttool/writer/level1/w_calculate.bas\
-   /qatesttool/writer/level1/w_chinesetranslate.bas\
-   /qatesttool/writer/level1/w_clipbrd.bas\
-   /qatesttool/writer/level1/w_contextmenu.bas\
-   /qatesttool/writer/level1/w_dropdownLB.bas\
-   /qatesttool/writer/level1/w_fields.bas\
-   /qatesttool/writer/level1/w_formatcharacter.bas\
-   /qatesttool/writer/level1/w_formatpage.bas\
-   /qatesttool/writer/level1/w_formatparagraph.bas\
-   /qatesttool/writer/level1/w_hhConversion.bas\
-   /qatesttool/writer/level1/w_insertgraphic.bas\
-   /qatesttool/writer/level1/w_lvl1.bas\
-   /qatesttool/writer/level1/w_menutools.bas\
-   /qatesttool/writer/level1/w_navigator.bas\
-   /qatesttool/writer/level1/w_numbering.bas\
-   /qatesttool/writer/level1/w_opt.bas\
-   /qatesttool/writer/level1/w_redlining.bas\
-   /qatesttool/writer/level1/w_search.bas\
-   /qatesttool/writer/level1/w_section.bas\
-   /qatesttool/writer/level1/w_sorting.bas\
-   /qatesttool/writer/level1/w_spellcheck.bas\
-   /qatesttool/writer/level1/w_stylist.bas\
-   /qatesttool/writer/level1/w_table.bas\
-   /qatesttool/writer/level1/w_textframes.bas\
-   /qatesttool/writer/level1/w_undo.bas\
-   /qatesttool/writer/level1/w_undo_history.bas\
-   /qatesttool/writer/level1/ww_opt.bas\
-   /qatesttool/writer/loadsave/w_exp_bin.bas\
-   /qatesttool/writer/loadsave/w_exp_xml1.bas\
-   /qatesttool/writer/loadsave/w_exp_xml2.bas\
-   /qatesttool/writer/loadsave/w_filter.bas\
-   /qatesttool/writer/loadsave/w_imp_bin.bas\
-   /qatesttool/writer/loadsave/w_imp_bugdoc.bas\
-   /qatesttool/writer/loadsave/w_imp_xml1.bas\
-   /qatesttool/writer/loadsave/w_imp_xml2.bas\
-   /qatesttool/writer/regression/w_bugtracker_p2_101000.bas\
-   /qatesttool/writer/regression/w_bugtracker_p2_102000.bas\
-   /qatesttool/writer/regression/w_bugtracker_p2_103000.bas\
-   /qatesttool/calc/level1/c_lvl1.bas\
-   /qatesttool/calc/options/c_opt.bas\
-   /qatesttool/calc/special/c_chinesetranslate.bas\
-   /qatesttool/calc/special/c_clipboardtest.bas\
-   /qatesttool/calc/special/c_namedrange.bas\
-   /qatesttool/calc/special/c_printrange.bas\
-   /qatesttool/calc/special/c_so7_pp1.bas\
-   /qatesttool/calc/special/fkt_test.bas\
-   /qatesttool/calc/special/keyboardaccessibility.bas\
-   /qatesttool/calc/special/menu_2.bas\
-   /qatesttool/calc/special/page_styles.bas\
-   /qatesttool/calc/special/validity.bas\
-   /qatesttool/chart/level1/ch_lvl1.bas\
-   /qatesttool/chart/special/chart_types.bas\
-   /qatesttool/math/level1/m_lvl1.bas\
-   /qatesttool/graphics/level1/d_export_graphic.bas\
-   /qatesttool/graphics/level1/g_accessability.bas\
-   /qatesttool/graphics/level1/g_area.bas\
-   /qatesttool/graphics/level1/g_arrangealign.bas\
-   /qatesttool/graphics/level1/g_autocorrection.bas\
-   /qatesttool/graphics/level1/g_character.bas\
-   /qatesttool/graphics/level1/g_clipboard.bas\
-   /qatesttool/graphics/level1/g_clipexport.bas\
-   /qatesttool/graphics/level1/g_convertto.bas\
-   /qatesttool/graphics/level1/g_crossfading.bas\
-   /qatesttool/graphics/level1/g_dimensions.bas\
-   /qatesttool/graphics/level1/g_edit.bas\
-   /qatesttool/graphics/level1/g_export_html.bas\
-   /qatesttool/graphics/level1/g_findreplace.bas\
-   /qatesttool/graphics/level1/g_format.bas\
-   /qatesttool/graphics/level1/g_group.bas\
-   /qatesttool/graphics/level1/g_imagemap.bas\
-   /qatesttool/graphics/level1/g_insert.bas\
-   /qatesttool/graphics/level1/g_line.bas\
-   /qatesttool/graphics/level1/g_load_save.bas\
-   /qatesttool/graphics/level1/g_navigator.bas\
-   /qatesttool/graphics/level1/g_paragraph.bas\
-   /qatesttool/graphics/level1/g_print.bas\
-   /qatesttool/graphics/level1/g_slidelayer.bas\
-   /qatesttool/graphics/level1/g_spellcheck.bas\
-   /qatesttool/graphics/level1/g_stylist.bas\
-   /qatesttool/graphics/level1/g_toolbars.bas\
-   /qatesttool/graphics/level1/g_tools.bas\
-   /qatesttool/graphics/level1/g_zoom.bas\
-   /qatesttool/graphics/level1/i_animation.bas\
-   /qatesttool/graphics/level1/i_export_graphic.bas\
-   /qatesttool/graphics/level1/i_headerfooter.bas\
-   /qatesttool/graphics/level1/i_slideshow.bas\
-   /qatesttool/graphics/level1/i_view.bas\
-   /qatesttool/graphics/options/d_opt.bas\
-   /qatesttool/graphics/options/i_opt.bas\
-   /qatesttool/xml/level1/calc_xml_7_export.bas\
-   /qatesttool/xml/level1/ch_xml_japanese_candlestick.bas\
-   /qatesttool/xml/level1/docbook_losa.bas\
-   /qatesttool/xml/level1/draw_xml_7_export.bas\
-   /qatesttool/xml/level1/impress_xml_7_export.bas\
-   /qatesttool/xml/level1/writer_xml_7_export.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Control_Autopilot.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Control_Calc.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Control_Clipboard.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Control_General.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Control_Several.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Grid_Control.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Property_Browser.bas\
-   /qatesttool/base/level1/controls/b_lvl1_Text_Control.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_ADO-Access.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_AdabasD.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_Addressbook.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_JDBC_MySQL.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_ODBC_MySQL.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_RegisterDatabase.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_Spreadsheet.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_Text.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_dBase.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_dBase_functions.bas\
-   /qatesttool/base/level1/datasources/b_lvl1_hsqldb.bas\
-   /qatesttool/base/level1/forms/b_lvl1_FormFilter.bas\
-   /qatesttool/base/level1/forms/b_lvl1_Forms.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_Copy_Table_Autopilot.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_Database_Wizard.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_FormAutopilot.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_QueryAutopilot.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_ReportAutopilot.bas\
-   /qatesttool/base/level1/wizards/b_lvl1_Table_Wizard.bas\
-   /qatesttool/base/level1/xforms/xf_lvl1_submission.bas\
-")
+# list of test to be started
+testList=
+if  test ! -f "$1" ; then
+    echo "Error: cannot read \"$1\", try --help" && exit 1;
+else
+    testList=`cat "$1" | sed "s|\#.*$||"`
+fi
 
+# list of tests to be skipped
+testBlackList=
+if test -n "$2" ; then
+    if test -a ! -f "$2" ; then
+	echo "Error: cannot read \"$2\", try --help" && exit 1;
+    else
+	testBlackList=`cat "$2" | sed "s|\#.*$||"`
+    fi
+fi
+    
 echo "Switching to en_US.UTF-8 locales!!!"
 export LANG=en_US.UTF-8
 
@@ -264,8 +94,13 @@ for test in $testList ; do
 	echo "Skipping test $test..."
     else
 	echo "Starting test $test..."
-        $testToolBin -run $testToolRoot$test
+	# first, remove the potentially broken user configuration
+	rm -rf $userConfigDir
+	$testToolBin -run $testToolRoot/$test
 	sleep 5
 	killall soffice.bin
+	# just to be sure
+	sleep 2
+	killall -9 soffice.bin
     fi
 done
