Check whether the userConfigDir variable is set correctly; also pass test.
* bin/test-ooo: check whether the userConfigDir variable is set
correctly; also pass test.list through dos2unix to avoid problems
on Windows systems

diff --git a/bin/test-ooo b/bin/test-ooo
--- a/bin/test-ooo
+++ b/bin/test-ooo
@@ -8,13 +8,13 @@
 
 
 #TESTTOOL=/opt/openoffice.org2.0/program/testtool.bin
-testToolBin=/usr/lib/ooo-2.1/program/testtool.bin
+export testToolBin=/usr/lib/ooo3/basis3.0/program/testtool.bin
 
 # where the qatesttool is stored (testcases)
-testToolRoot=/test/OOo/qa/qatesttool
+export testToolRoot=/test/OOo/qa/qatesttool
 
 # path to the user configuration directory
-userConfigDir=$HOME/.ooo-2.0
+export userConfigDir=$HOME/.ooo3/
 
 # all tests will be skipped until this script name is found
 # define empty string to do not skip any test
@@ -45,12 +45,17 @@ if test -z "$1" -o "$1" = "--help" -o $# -gt 2 ; then
     usage && exit 1;
 fi
 
+if ! which dos2unix >/dev/null 2>&1 ; then
+    echo "Error: dos2unix utility is not installed"
+    exit 1;
+fi
+
 # list of test to be started
 testList=
 if  test ! -f "$1" ; then
     echo "Error: cannot read \"$1\", try --help" && exit 1;
 else
-    testList=`cat "$1" | sed "s|\#.*$||"`
+    testList=`cat "$1" | dos2unix | sed "s|\#.*$||"`
 fi
 
 # list of tests to be skipped
@@ -59,7 +64,7 @@ if test -n "$2" ; then
     if test ! -f "$2" ; then
 	echo "Error: cannot read \"$2\", try --help" && exit 1;
     else
-	testBlackList=`cat "$2" | sed "s|\#.*$||"`
+	testBlackList=`cat "$2" | dos2unix | sed "s|\#.*$||"`
     fi
 fi
     
@@ -79,6 +84,27 @@ is_blacklisted()
     return 1
 }
 
+run_test()
+{
+    test="$1"
+    # first, remove the potentially broken user configuration
+    rm -rf "$userConfigDir"
+    "$testToolBin" -run "$test"
+    sleep 5
+    killall soffice.bin
+    # just to be sure
+    sleep 2
+    killall -9 soffice.bin
+}
+
+echo "Checking userConfigDir variable..."
+run_test "$testToolRoot/global/tools/closeoffice.bas"
+if ! test -d "$userConfigDir" ; then
+    echo "Error: The user config directory does not exists: $userConfigDir"
+    echo "       Please, check the setting of the variable userConfigDir in $0"
+    exit 1;
+fi
+
 # will we skip any test?
 test -n "$SKIP_TO_TEST" && skip_tests=true || skip_tests=false
 
@@ -94,13 +120,6 @@ for test in $testList ; do
 	echo "Skipping test $test..."
     else
 	echo "Starting test $test..."
-	# first, remove the potentially broken user configuration
-	rm -rf $userConfigDir
-	$testToolBin -run $testToolRoot/$test
-	sleep 5
-	killall soffice.bin
-	# just to be sure
-	sleep 2
-	killall -9 soffice.bin
+	run_test "$testToolRoot/$test"
     fi
 done
