Scott Clayton's ODMA fix for GroupWise.
* patches/OOO_1_1/win32-odma-gw-fix.diff: Scott Clayton's
ODMA fix for GroupWise.

* bin/unpack, bin/setup.in: re-enable ODMA bits.
* download.in: re-instate odma download for win32.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -58,7 +58,7 @@ cd $BUILDDIR
 if test "z$BUILD_WIN32" != "z"; then
     check_file $UNICOWS_SRC
     check_file $DBGINST_SRC
-#    check_file $ODMA_SRC
+    check_file $ODMA_SRC
 fi
 
 if test "z$ENABLE_JAVA" = "zyes" &&
@@ -105,24 +105,24 @@ chmod a+x $OOBUILDDIR/config_office/oowintool
 # Win32 prerequisites ...
 if test "z$BUILD_WIN32" != "z"; then
 
-	    # ODMA
-#	    cd $BUILDDIR;
-#	    DEST=$OOBUILDDIR/ucb/source/ucp/odma
-#	    if test ! -f $DEST/ODMA.H; then
-#		echo -n "Extracting ODMA SDK "
-#		unzip -o $ODMA_SRC
-#		TARGET=Odma20.exe
-#		if test ! -f $TARGET; then
-#		    echo "failed";
-#		    exit 1;
-#		fi
-#		mkdir -p $DEST
-#		cd $DEST
-#		unzip -o $BUILDDIR/$TARGET
-#		echo "done";
-#	    else
-#		echo "Already have ODMA SDK";
-#	    fi
+    # ODMA
+    cd $BUILDDIR;
+    DEST=$OOBUILDDIR/ucb/source/ucp/odma
+    if test ! -f $DEST/ODMA.H; then
+	echo -n "Extracting ODMA SDK "
+	unzip -o $ODMA_SRC
+	TARGET=Odma20.exe
+	if test ! -f $TARGET; then
+	    echo "failed";
+	    exit 1;
+	fi
+	mkdir -p $DEST
+	cd $DEST
+	unzip -o $BUILDDIR/$TARGET
+	echo "done";
+    else
+	echo "Already have ODMA SDK";
+    fi
 
     # dbghelp
     cd $BUILDDIR;
