In a Win32 build, require gdiplus.
* bin/unpack: In a Win32 build, require gdiplus.dll already at
this stage (config_office/configure will also require it), and
copy it into $OOBUILDDIR/external/gdiplus. Thus it's enough to
download it once into src and it gets copied automatically into
each milestone you build.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -52,6 +52,18 @@ if test "z$BUILD_WIN32" != "z"; then
     check_file $SRCDIR/libIDL-0.6.8.tar.gz
     check_file $SRCDIR/libIDL-0.6.8-ooo.patch
     check_file $SRCDIR/wintools.zip
+    echo -n "Looking for $SRCDIR/gdiplus.dll ... "
+    if test ! -f $SRCDIR/gdiplus.dll; then
+	echo "missing"
+	echo "Get it from the Microsoft site and put it into $SRCDIR"
+	echo "You may have to search Microsoft's website."
+	echo "Last time it was seen at: http://www.microsoft.com/downloads/details.aspx?familyid=6A63AB9C-DF12-4D41-933C-BE590FEAA05A&displaylang=en"
+	echo "Note that the download requires Genuine Windows validation"
+	echi "and can't easily be automated."
+	exit 1
+    else
+	echo "ok"
+    fi
 fi
 
 if test "z$SYSTEM_GCC" = "z"; then
@@ -160,6 +172,12 @@ if test "z$BUILD_WIN32" != "z"; then
 #    else
 #	echo "Already have ODMA SDK";
 #    fi
+
+    # gdiplus.dll
+    cd $BUILDDIR;
+    if test ! -f $OOBUILDDIR/external/gdiplus/gdiplus.dll; then
+	cp -p $SRCDIR/gdiplus.dll $OOBUILDDIR/external/gdiplus/gdiplus.dll
+    fi
 
     # dbghelp
     cd $BUILDDIR;
