Add 'sloppy patching' support: only apply bits of patch for which we have top level directories: add --pieces option.
* bin/sloppypatch.pl, patches/apply.pl.in: add 'sloppy patching'
support: only apply bits of patch for which we have top level
directories: add --pieces option.

* configure.in, bin/unpack: add PIECES flag - and unpack
~nothing but this one piece.
* Makefile.shared - nearly shot myself seeing the FLAGS
cut/paste there: we need a shared helper to spawn to set
these [!] Quote OOO_LANGS to stop it blowing the shell's
arg count (urgh).

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -17,12 +17,16 @@ fi
 
 check_tarball()
 {
-    $echo_n "Looking for $1 ... $echo_c";
-    if test -f $1; then
-	echo "ok"
+    if test "z$PIECE" != "z"; then
+	echo "skipping looking for $1 ...";
     else
-	echo "missing the $1 archive; run './download'"
-	exit 1;
+	$echo_n "Looking for $1 ... $echo_c";
+	if test -f $1; then
+		echo "ok"
+	else
+		echo "missing the $1 archive; run './download'"
+		exit 1;
+	fi
     fi
 }
 
@@ -47,12 +51,18 @@ if test "z$SYSTEM_GCC" = "z"; then
 	check_tarball $BINUTILS_TARBALL
     fi
 fi
-
+	
+# this will become the 'normal' way to do an all-through build name is misleading
 if test "z$SPLIT" != "z"; then
-	CORE_PKGS="sdk ure base calc l10n writer impress artwork filters testing bootstrap libs-gui libs-core libs-extern extensions postprocess"
+	if test "z$PIECE" != "z"; then
+		CORE_PKGS=$PIECE
+	else
+		CORE_PKGS="sdk ure base calc l10n writer impress artwork filters testing bootstrap libs-gui libs-core libs-extern extensions postprocess"
+	fi
 	for pkg in $CORE_PKGS; do
 		check_tarball "$OOO_SPLIT_PREFIX$pkg.tar.bz2"
 	done
+# this is the legacy source splitting
 else
 	CORE_PKGS=
 	check_tarball $OOO_TARBALL
@@ -212,16 +222,20 @@ esac
 # copy in unowinreg.dll if we need to
 # it is necessary in ODK
 # it can be built even on linux by mingw32, though
+if test "z$PIECE" == "z"; then
 if test "$USE_PREBUILD_UNOWINREG_DLL" = "YES" ; then
     $GNUCP -f $SRCDIR/unowinreg.dll $OOBUILDDIR/external/unowinreg/ || exit 1;
+fi
 fi
 
 # copy in misc Mono related dlls if we need to
 # we can't build them on Unix.
 CLI_TYPES=cli_types.dll
+if test "z$PIECE" == "z"; then
 if test -f "$SRCDIR/$CLI_TYPES"; then
     mkdir -p $OOBUILDDIR/external/cli
     $GNUCP -af $SRCDIR/$CLI_TYPES $SRCDIR/cli_types_bridgetest.dll $OOBUILDDIR/external/cli
+fi
 fi
 
 # Win32 prerequisites ...
@@ -447,6 +461,8 @@ if test -d $OOBUILDDIR/ooo_custom_images/tango/res ; then
     $GNUCP $TOOLSDIR/src/tango_mainapp_16.png $OOBUILDDIR/ooo_custom_images/tango/res/mainapp_16.png || exit 1;
 fi
 
+if test "z$PIECE" == "z"; then
+
 if test "x$OOO_EXTRA_ARTWORK" != "x"; then
 # Html export rulers etc.
     cd $OOBUILDDIR
@@ -585,3 +601,4 @@ echo "Copying extra command images"
 $GNUCP -f $TOOLSDIR/src/icons/*.png $OOBUILDDIR/default_images/res/commandimagelist/ || exit 1
 $GNUCP -f $TOOLSDIR/src/icons/tango/*.png $OOBUILDDIR/ooo_custom_images/tango/res/commandimagelist/ || exit 1
 
+fi # PIECES hack
