Error out if writerfilter isn't there, as discussed on mailing list

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -497,6 +497,9 @@ if test -f $SRCDIR/$WRITERFILTER_MODULE_TARBALL; then
     cd $OOBUILDDIR
     rm -rf writerfilter
     ($OOO_DECOMPRESS_CMD $SRCDIR/$WRITERFILTER_MODULE_TARBALL | $GNUTAR xpf - ) || exit 1
+else
+    echo "The writerfilter module is missing - please run the download script."
+    exit 1
 fi
 
 # OxygenOffice extras
