Create build/ don't check for stuff until it's there.
* bin/unpack: create build/ don't check for stuff
until it's there.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -51,21 +51,7 @@ if test "z$BUILD_WIN32" != "z"; then
     check-tarball $OOO_SCALED_ICONS_TARBALL
 fi
 
-if test "z$SYSTEM_GCC" = "z"; then
-    if test "z$ENABLE_JAVA" = "zyes" &&
-	test ! -d "$BUILDDIR/$JDK_VER" &&
-	test "z$JDK_HOME" = "z"; then
-        echo "Missing the JDK";
-    fi
-    
-    if test ! -d "$BUILDDIR/$GCC_VER" ||
-	test ! -d "$BUILDDIR/$OOO_ICONS_VER" ||
-	test ! -d "$BUILDDIR/$BINUTILS_VER"; then
-        echo "Missing some of the helper source";
-        exit 1;
-    fi
-fi
-
+mkdir -p $BUILDDIR
 cd $BUILDDIR
 
 if test "z$BUILD_WIN32" != "z"; then
@@ -164,5 +150,20 @@ if test "z$BUILD_WIN32" != "z"; then
 	echo "done";
     else
 	echo "Already have unicows";
+    fi
+fi
+
+if test "z$SYSTEM_GCC" = "z"; then
+    if test "z$ENABLE_JAVA" = "zyes" &&
+	test ! -d "$BUILDDIR/$JDK_VER" &&
+	test "z$JDK_HOME" = "z"; then
+        echo "Missing the JDK";
+    fi
+    
+    if test ! -d "$BUILDDIR/$GCC_VER" ||
+	test ! -d "$BUILDDIR/$OOO_ICONS_VER" ||
+	test ! -d "$BUILDDIR/$BINUTILS_VER"; then
+        echo "Missing some of the helper source";
+        exit 1;
     fi
 fi
