Drop dos2unixifying build-java-target.
* bin/unpack: Drop dos2unixifying build-java-target.diff, not
needed any more. Fix a couple of "test" syntax errors introduced
by me on 2008-06-12. Look for the VC 9.0 CRT merge modules and
copy them into external/msm90.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -263,9 +263,6 @@ fi
 # Win32 prerequisites ...
 if test "z$BUILD_WIN32" != "z"; then
 
-    echo "Removing CRs from a couple of files"
-    dos2unix $SRCDIR/../patches/src680/build-java-target.diff
-
     # gdiplus.dll
     cd $BUILDDIR;
     if test -f $OOBUILDDIR/external/gdiplus/gdiplus.dll; then
@@ -386,15 +383,31 @@ if test "z$BUILD_WIN32" != "z"; then
     fi
 
     if test -f $OOBUILDDIR/external/msvcp71/msvcr71.dll -a \
-       test -f $OOBUILDDIR/external/msvcp71/msvcp71.dll; then
+            -f $OOBUILDDIR/external/msvcp71/msvcp71.dll; then
 	echo "Already have msvcr71.dll and msvcp71.dll"
     else
 	$GNUCP -p $SRCDIR/msvcr71.dll $OOBUILDDIR/external/msvcp71
 	$GNUCP -p $SRCDIR/msvcp71.dll $OOBUILDDIR/external/msvcp71
     fi
 
-    if test -f $OOBUILDDIR/external/msi/instmsia.exe -a \
-       test -f $OOBUILDDIR/external/msi/instmsiw.exe; then
+    if test -f $OOBUILDDIR/external/msm90/Microsoft_VC90_CRT_x86.msm -a \
+            -f $OOBUILDDIR/external/msm90policy_9_0_Microsoft_VC90_CRT_x86.msm; then
+	echo "Already have Microsoft_VC90_CRT_x86.msm and policy_9_0_Microsoft_VC90_CRT_x86.msm"
+    elif test -f "$COMMONPROGRAMFILES/Merge Modules/Microsoft_VC90_CRT_x86.msm" -a \
+              -f "$COMMONPROGRAMFILES/Merge Modules/policy_9_0_Microsoft_VC90_CRT_x86.msm"; then
+	echo "Copying Microsoft VC9.0 CRT Merge Modules"
+	$GNUCP -p "$COMMONPROGRAMFILES/Merge Modules/Microsoft_VC90_CRT_x86.msm" $OOBUILDDIR/external/msm90
+	$GNUCP -p "$COMMONPROGRAMFILES/Merge Modules/policy_9_0_Microsoft_VC90_CRT_x86.msm" $OOBUILDDIR/external/msm90
+    else
+	echo "Missing Microsoft VC9.0 CRT Merge Modules:"
+	echo "Microsoft_VC90_CRT_x86.msm and policy_9_0_Microsoft_VC90_CRT_x86.msm."
+	echo "Did not find them in $COMMONPROGRAMFILES/Merge Modules"
+	echo "Do you have a Visual Studio 2008 installation?"
+	exit 1
+    fi
+ 
+   if test -f $OOBUILDDIR/external/msi/instmsia.exe -a \
+           -f $OOBUILDDIR/external/msi/instmsiw.exe; then
 	echo "Already have instmsia.exe and instmsiw.exe"
     else
 	$GNUCP -p $SRCDIR/instmsia.exe $OOBUILDDIR/external/msi
