Add the possibility to use git to download the up-stream sources.
Renamed the old --with-git ooo-build configure switch to --with-git-managed,
and introduced a new --with-git meaning that git will be used to clone the
up-stream sources in src/clone/* [first time use], or to fetch the latest
tags/branches from there [the rest], considerably reducing the time &
bandwidth needed to get newer milestones.

* Makefile.shared: OOO_GIT -> OOO_GIT_MANAGED.
* bin/piece/unpack-extras: Create a missing directory if needed.
* bin/setup.in: Export OOO_GIT and GITTAG.
* bin/unpack: git checkout/rsync to copy the sources from src/clone to
  build/<tag>.
* configure.in: --with-git and --with-git-managed.
* download.in: git clone/fetch to get the latest updates.
* src/.gitignore: Ignore src/clone.

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -15,6 +15,8 @@ else
     echo_n=echo echo_c='\c'
 fi
 
+#"# don't confuse vim's syntax highlighting ;-)
+
 check_tarball()
 {
     if test "z$PIECE" != "z"; then
@@ -27,6 +29,23 @@ check_tarball()
 		echo "missing the $1 archive; run './download'"
 		exit 1;
 	fi
+    fi
+}
+
+check_git_repo()
+{
+    tree="$SRCDIR/clone/$1"
+    $echo_n "Looking for $GITTAG in $tree ... $echo_c";
+    if cd "$tree" >/dev/null 2>&1 ; then
+        if git show $GITTAG >/dev/null 2>&1 ; then
+            echo "ok"
+        else
+            echo "missing the tag; run './download'"
+            exit 1;
+        fi
+    else
+        echo "missing the $tree clone; run './download'"
+        exit 1;
     fi
 }
 
@@ -53,19 +72,34 @@ if test "z$SYSTEM_GCC" = "z"; then
 fi
 
 # this will become the 'normal' way to do an all-through build name is misleading
-if test "z$SPLIT" = "zyes" ; then
+ALL_CORE_PKGS="sdk ure base calc help extras writer impress artwork filters testing bootstrap libs-gui libs-core libs-extern libs-extern-sys components postprocess extensions"
+if test "z$OOO_GIT" = "zNO" ; then
+    if test "z$SPLIT" = "zyes" ; then
 	if test "z$PIECE" != "z"; then
-		CORE_PKGS=$PIECE
+	    CORE_PKGS=$PIECE
 	else
-		CORE_PKGS="sdk ure base calc help extras writer impress artwork filters testing bootstrap libs-gui libs-core libs-extern libs-extern-sys components postprocess extensions"
+	    CORE_PKGS=$ALL_CORE_PKGS
 	fi
 	for pkg in $CORE_PKGS; do
-		check_tarball "$OOO_SPLIT_PREFIX$pkg.tar.bz2"
+	    check_tarball "$OOO_SPLIT_PREFIX$pkg.tar.bz2"
 	done
-# this is the legacy source splitting
-else
+    # this is the legacy source splitting
+    else
 	CORE_PKGS=
 	check_tarball $OOO_TARBALL
+    fi
+else
+    if test "z$PIECE" != "z"; then
+        CORE_PKGS=$PIECE
+    else
+        CORE_PKGS=$ALL_CORE_PKGS
+    fi
+    if test "z$OOO_LANGS" != "zen-US"; then
+        CORE_PKGS="$CORE_PKGS l10n"
+    fi
+    for pkg in $CORE_PKGS ; do
+        check_git_repo $pkg
+    done
 fi
 
 mkdir -p $BUILDDIR
@@ -181,10 +215,11 @@ if test "z$SYSTEM_GCC" = "z"; then
 fi
 
 echo "Unpacking OO.o build tree - [ go and have some $DRINK ] ..."
-if test "z$SPLIT" != "zyes"; then
+if test "z$OOO_GIT" = "zNO" ; then
+    if test "z$SPLIT" != "zyes"; then
 	echo "Unpacking $OOO_TARBALL..."
 	($OOO_DECOMPRESS_CMD $SRCDIR/$OOO_TARBALL | $GNUTAR xpf - ) || exit 1
-else # split packages
+    else # split packages
 	if test -d $OOBUILDDIR; then
 	    echo "	removing old build dir: $OOBUILDDIR"
 	    rm -rf $OOBUILDDIR
@@ -203,6 +238,27 @@ else # split packages
 		echo "Unpacking setup_native .txt pieces"
 		($OOO_DECOMPRESS_CMD $SRCDIR/setup_native_packinfo-ooo310-m2.tar.bz2 | $GNUTAR xpf - ) || exit
 	fi
+    fi
+else
+    if test -d $OOBUILDDIR; then
+        echo "* removing old build dir: $OOBUILDDIR"
+        rm -rf $OOBUILDDIR
+    fi
+    mkdir $OOBUILDDIR
+    for pkg in $CORE_PKGS; do
+        tree=$SRCDIR/clone/$pkg
+        echo "* checking out $CVSTAG in $pkg..."
+        (
+            cd $tree
+            if git show $CVSTAG >/dev/null 2>&1 ; then
+                git checkout $CVSTAG || exit 1
+            else
+                git checkout -b $CVSTAG $GITTAG || exit 1
+            fi
+        )
+        echo "* copying it into place..."
+        rsync -a --exclude .git $tree/* $OOBUILDDIR/
+    done
 fi
 
 # original upstream sources
