Skip gtk+2.
* configure.in: skip gtk+2.0 checks on win32
* download.in, bin/unpack: skip the ODMA package for now

diff --git a/bin/unpack b/bin/unpack
--- a/bin/unpack
+++ b/bin/unpack
@@ -50,7 +50,7 @@ cd $BUILDDIR
 if test "z$BUILD_WIN32" != "z"; then
     check_file $UNICOWS_SRC
     check_file $DBGINST_SRC
-    check_file $ODMA_SRC
+#    check_file $ODMA_SRC
 fi
 
 if test "z$SYSTEM_GCC" = "z"; then
@@ -89,23 +89,24 @@ if test "z$BUILD_WIN32" != "z"; then
     tar $OOO_UNTAR_OPTIONS $SRCDIR/$OOO_SYSTEM_TARBALL || exit 1
 
     # ODMA
-    cd $BUILDDIR;
-    DEST=$OOBUILDDIR/ucb/source/ucp/odma
-    if test ! -f $DEST/ODMA.H; then
-	echo -n "Extracting ODMA SDK "
-	unzip -o $ODMA_SRC
-	TARGET=Odma20.exe
-	if test ! -f $TARGET; then
-	    echo "failed";
-	    exit 1;
-	fi
-	mkdir -p $DEST
-	cd $DEST
-	unzip -o $BUILDDIR/$TARGET
-	echo "done";
-    else
-	echo "Already have ODMA SDK";
-    fi
+	echo "ODMA disabled for now."
+#    cd $BUILDDIR;
+#    DEST=$OOBUILDDIR/ucb/source/ucp/odma
+#    if test ! -f $DEST/ODMA.H; then
+#	echo -n "Extracting ODMA SDK "
+#	unzip -o $ODMA_SRC
+#	TARGET=Odma20.exe
+#	if test ! -f $TARGET; then
+#	    echo "failed";
+#	    exit 1;
+#	fi
+#	mkdir -p $DEST
+#	cd $DEST
+#	unzip -o $BUILDDIR/$TARGET
+#	echo "done";
+#    else
+#	echo "Already have ODMA SDK";
+#    fi
 
     # dbghelp
     cd $BUILDDIR;
