Add bash completion also to the split build
* bin/piece/file-list-postprocess: add bash completion also to the
split build

* src/sg3.sdg, src/sg3.thm, src/sg3.sdv, bin/piece/install-bootstrap:
* bin/piece/file-list-l10n, bin/piece/sys-setup.in: use the hacked
"Backgrounds" gallery for Novell (added the Draft.jpg picture)

* bin/java-set-classpath.in: fix for the 3-layer system
* bin/piece/file-list-postprocess: install java-set-classpath in
the split build as well (bnc#465250)

* src/layout/Makefile.am: pack the layout icons to the released tarball
* bin/piece/install-bootstrap: put the extra icons to the bootstrap
package
* bin/unpack, bin/install-artwork: copy the extra icons in
install-artwork insterad of bin/unpack; then they are used also
in the split build (bnc#458929)

diff --git a/bin/piece/file-list-l10n b/bin/piece/file-list-l10n
--- a/bin/piece/file-list-l10n
+++ b/bin/piece/file-list-l10n
@@ -13,6 +13,27 @@ cp -a $OO_TOOLSDIR/../src/main_transform.xsl $DESTDIR$OO_INSTDIR/basis$VERSION/h
 echo "%dir $OO_INSTDIR/basis$VERSION/help" >>files-$piece.txt
 echo "$OO_INSTDIR/basis$VERSION/help/main_transform.xsl" >>files-$piece.txt
 
+if test "$VENDORNAME" = "Novell" ; then
+    # We want to update an existing gallery. Unfortunately, gengal does not work
+    # because of missing services.rdb, ... Therefore we need to use a prebuilt
+    # version
+    echo "Adding Novell specific Draft.jpg to Backgrounds gallery..."
+    GAL_DIR=$OO_INSTDIR/basis3.0/share/gallery
+    if test `du --block-size=1 --apparent-size $DESTDIR$GAL_DIR/sg3.sdg | cut -f1` -eq 270058 ; then
+	cp "$OO_TOOLSDIR/../src/Draft.jpg" "$DESTDIR$GAL_DIR/www-back/" || exit 1;
+	chmod 644 $DESTDIR$GAL_DIR/www-back/Draft.jpg || exit 1;
+	echo $GAL_DIR/www-back/Draft.jpg >>files-$piece.txt
+	for file in sg3.sdg sg3.sdv sg3.thm ; do
+	    cp -f "$OO_TOOLSDIR/../src/$file" "$DESTDIR$GAL_DIR/$file" || exit 1;
+	    chmod 644 "$DESTDIR$GAL_DIR/$file" || exit 1;
+	done
+    else
+	echo "Error: The upstream gallery sg3.sdg has changed. Please, update the prebuilt"
+	echo "       Novell variant in $OO_TOOLSDIR/../src/"
+	exit 1;
+    fi
+fi
+
 # prune redundant files the scp2 likes to make for us
 remove_file "files-$piece.txt" "$OO_INSTDIR/basis-link"
 remove_file "files-$piece.txt" "$OO_INSTDIR/basis$VERSION/ure-link"
