Fix build with ooo310-m2
* patches/dev300/piece-helpcontent2.diff:
* patches/dev300/piece-writer2latex.diff:
* patches/dev300/piece-extensions.diff:
* patches/dev300/piece-reportdesign.diff:
* patches/dev300/piece-sw.diff:
* patches/dev300/piece-vbahelper.diff:
* patches/dev300/apply: fix build with ooo310-m2

* patches/dev300/piece-scp2.diff: add hack to build with internal icu
on older systems

* patches/dev300/wpgimporter.diff: fix context to apply correctly

* bin/piece/sys-setup.in: fix link flags to search the system solver
before /usr/lib; the internal libraries must be preferred if they
are they are enabled and built

* configure.in, src/helpcontent2/*, src/main_transform.xsl:
* bin/piece/file-list-postprocess, bin/piece/install-bootstrap:
* bin/piece/file-list-l10n, bin/piece/file-list-help: hack to install
all the common files in the main OpenOffice.org package

* bin/piece/file-list-artwork: remove execuable rights from icons

* bin/piece/desktop-support-app: pack also the system icon directories
on older distributions to pass the build check

* bin/piece/build-generic, bin/applyflags, doc/split.txt: use
applyflags also for the split build; also check the file
ooo-build/apply-additional-sections for more extra selected sections;
it is useful to do test builds with Experimental sections if they
affect only one piece

diff --git a/bin/piece/file-list-help b/bin/piece/file-list-help
--- a/bin/piece/file-list-help
+++ b/bin/piece/file-list-help
@@ -10,8 +10,18 @@ $OO_TOOLSDIR/piece/sort-l10n $piece $ooo_build_tag $DESTDIR
 
 # put the rest into the common file list
 $OO_TOOLSDIR/piece/merge-file-lists "files-$piece.txt" $DESTDIR/gid_*
-# main_transform.xsl will be in l10n-extras
-remove_file "files-$piece.txt" $OO_INSTDIR/basis$VERSION/help/main_transform.xsl
+# FIXME: remove files from the top dir; they are common for all localizations
+#        and must be included in the main package (postprocess)
+for file in main_transform.xsl idxcaption.xsl idxcontent.xsl ; do
+    if test `du --block-size=1 --apparent-size $DESTDIR$OO_INSTDIR/basis$VERSION/help/$file | cut -f1` -eq \
+            `du --block-size=1 --apparent-size $OO_TOOLSDIR/../src/helpcontent2/$file | cut -f1` ; then
+	remove_file "files-$piece.txt" $OO_INSTDIR/basis$VERSION/help/$file
+    else
+	echo "Error: The file \"$file\" has changed in the sources"
+	echo "       Please, update the prebuilt variant in $OO_TOOLSDIR/../src/helpcontent2"
+	exit 1;
+    fi
+done
 # FIXME: hid.lst will be in testtool package (built in ?)
 remove_file "files-$piece.txt" $OO_INSTDIR/basis$VERSION/program/hid.lst
 # non-wanted mess
