Split out the extras unpack pieces.
* bin/unpack, bin/piece/unpack-extras: split out the
extras unpack pieces.
* bin/pieces/*, scratch/split/*: yet more work.

diff --git a/bin/piece/sys-setup b/bin/piece/sys-setup
--- a/bin/piece/sys-setup
+++ b/bin/piece/sys-setup
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+if test "z$OO_INSTDIR" == "z"; then
+    echo "Error: missing oo instdir"
+    exit 1
+fi
+# a saneish default directory for the solver
+if test "z$OO_SOLVERDIR" == "z"; then
+    export OO_SOLVERDIR=$OO_INSTDIR/solver
+fi
+
 # installed system libraries
 URE_DIR=$OO_INSTDIR/ure
 INSTALL_DIR=$OO_INSTDIR/basis3.0/program
