More bits on mac build
* patches/test/macbuild.diff: more bits on mac build

diff --git a/patches/test/macbuild.diff b/patches/test/macbuild.diff
--- a/patches/test/macbuild.diff
+++ b/patches/test/macbuild.diff
@@ -11,6 +11,31 @@ Index: bin/build-ooo
      if ! test -f /proc/cpuinfo; then
          echo "Looks like proc isn't mounted - this means almost certain"
          echo "Java related weird build failure: please check /proc"
+Index: bin/ooinstall
+===================================================================
+--- bin/ooinstall	(revision 13863)
++++ bin/ooinstall	(working copy)
+@@ -32,13 +32,18 @@
+ }
+ 
+ sub wanted {
++    my $path_to_unopkg="$path/program";
++    if ( $^O =~ /darwin/i )
++    {
++        $path_to_unopkg="$path/OpenOffice.org.app/Contents/MacOS";
++    }
+     -f $_ 
+ 	&& /.*\.oxt$/
+-	&& system ( "LD_LIBRARY_PATH='' $path/program/unopkg add -v --shared $File::Find::name" )
++	&& system ( "LD_LIBRARY_PATH='' $path_to_unopkg/unopkg add -v --shared $File::Find::name" )
+ 	&& die "Cannot install $_ extension!";
+ }
+ 
+-( -f "/proc/meminfo" ) || die "The installer cannot work without javaldx running, which requires /proc to be mounted";
++( $^O =~ /darwin/i ) || ( -f "/proc/meminfo" ) || die "The installer cannot work without javaldx running, which requires /proc to be mounted";
+ 
+ suck_setup ("./setup") || suck_setup ("bin/setup") || die "can't find bin/setup";
+ 
 Index: configure.in
 ===================================================================
 --- configure.in	(revision 13863)
