Support ooo-build patches localization
* po/Makefile.am, bin/po2sdf, bin/Makefile.am, bin/localize-ooo:
* doc/localization.txt, po/README: support ooo-build patches
localization
* po/ooo-build.sdf, po/ooo-build.pot: initial sdf and pot file
* po/ooo-build-cs.po, po/ooo-build-cs.sdf: sample partial Czech
translation

Note that it uses the prebuilt sdf files to avoid build dependency
on translate-toolkit. We do not have it on older distros, ...

Also the extracting of the ooo-build-specific strings is rather
painful and must be done offline. Feel free to send patches ;-)

diff --git a/po/Makefile.am b/po/Makefile.am
--- a/po/Makefile.am
+++ b/po/Makefile.am
@@ -1,1 +1,29 @@
-EXTRA_DIST=${wildcard *.po} ChangeLog POTFILES.in
+EXTRA_DIST=${wildcard *.po} \
+	${wildcard *.sdf} \
+	ooo-build.pot \
+	README \
+	ChangeLog \
+	POTFILES.in
+
+ooo_build_po_files = ${wildcard ooo-build-*.po}
+
+update-sdf: $(ooo_build_po_files:ooo-build-%.po=ooo-build-%.sdf)
+
+ooo-build.pot: ooo-build.sdf /usr/bin/oo2po
+	oo2po -P --multifile=onefile ooo-build.sdf $@
+
+ooo-build-*.po: ooo-build.pot /usr/bin/pot2po
+	pot2po -t $@ -i ooo-build.pot -o $@.new
+	mv $@.new $@
+
+ooo-build-%.sdf: ooo-build-%.po ooo-build.sdf /usr/bin/po2oo ../bin/po2sdf
+	../bin/po2sdf $* ooo-build.sdf $< $@
+
+/usr/bin/oo2po /usr/bin/pot2po /usr/bin/po2po:
+	echo "Error: $@ does not exit" ; \
+	echo "       You need to install translate-toolkit, see" ; \
+	echo "       http://translate.sourceforge.net/wiki/start" ; \
+	echo "       The package for openSUSE it named python-translate-toolkit" ; \
+	echo "       and can be found at" ; \
+	echo "       http://download.opensuse.org/repositories/OpenOffice.org:/EXTRAS/" ; \
+	exit 1
