Hack out ANT check, we hardcode it anyway for now and aren't allowed to require $ANT_HOME/bin/ant be there.
* patches/src680/ant-only-main-classes-hack.diff: hack out ANT check,
we hardcode it anyway for now and aren't allowed to require
$ANT_HOME/bin/ant be there...
* distro-configs/Debian.conf.in: ants home is /usr/share/ant1.6;
doesn't affect anything yet (see above), but when configure is
patched to do a suitable check for Debian this helps ;-)

diff --git a/patches/src680/ant-only-main-classes-hack.diff b/patches/src680/ant-only-main-classes-hack.diff
--- a/patches/src680/ant-only-main-classes-hack.diff
+++ b/patches/src680/ant-only-main-classes-hack.diff
@@ -30,3 +30,133 @@ diff -u -u -r1.26 ant.mk
  
  # --- TARGETS -----------------------------------------------------
  
+Index: configure.in
+===================================================================
+RCS file: /cvs/tools/config_office/configure.in,v
+retrieving revision 1.101
+diff -u -u -r1.101 configure.in
+--- config_office/configure.in	1 Mar 2005 09:38:16 -0000	1.101
++++ config_office/configure.in	11 Mar 2005 10:22:43 -0000
+@@ -3172,105 +3172,6 @@
+ AC_SUBST(USE_XINERAMA)
+ AC_SUBST(XINERAMA_LINK)
+ 
+-dnl ===================================================================
+-dnl Test for the presence of Ant and that it works
+-dnl ===================================================================
+-
+-if test "$SOLAR_JAVA" != ""; then
+-ANT_HOME=; export ANT_HOME
+-WITH_ANT_HOME=; export WITH_ANT_HOME
+-if test -z "$with_ant_home"; then
+-   AC_PATH_PROGS(ANT, [jakarta-ant ant ant.sh ant.bat])
+-else
+-   AC_PATH_PROGS(ANT, [jakarta-ant ant ant.sh ant.bat],,$with_ant_home/bin:$PATH)
+-   WITH_ANT_HOME=$with_ant_home
+-fi
+-
+-if test -z "$ANT"; then
+-  AC_MSG_ERROR([Ant not found - Make sure it's in the path or use --with-ant-home])
+-else
+-  # resolve relative or absolute symlink
+-  while test -h "$ANT"; do
+-     a_cwd=`pwd`
+-     a_basename=`basename "$ANT"`
+-     a_script=`ls -l "$ANT" | sed "s/.*${a_basename} -> //g"`
+-     cd "`dirname "$ANT"`"
+-     cd "`dirname "$a_script"`"
+-     ANT="`pwd`"/"`basename "$a_script"`"
+-     cd "$a_cwd"
+-  done
+-  AC_MSG_CHECKING([if $ANT works])
+-cat > conftest.java << EOF
+-    public class conftest {
+-	int testmethod(int a, int b) {
+-            return a + b;
+-	}
+-    }
+-EOF
+-
+-cat > conftest.xml << EOF
+-    <project name="conftest" default="conftest">
+-	<target name="conftest">
+-            <javac srcdir="." includes="conftest.java">
+-	    </javac>
+-	</target>
+-    </project>
+-EOF
+-
+-  if test "$JDK" = "gcj"; then
+-    ant_cmd="$ANT -Dbuild.compiler=gcj -buildfile conftest.xml 1>&2"
+-  else
+-    ant_cmd="$ANT -buildfile conftest.xml 1>&2"
+-  fi
+-  AC_TRY_EVAL(ant_cmd)
+-  if test $? = 0 && test -f ./conftest.class ; then
+-    AC_MSG_RESULT([Ant works]) 
+-    if test -z "$WITH_ANT_HOME"; then
+-        ANT_HOME=`echo $ANT | $SED -n "s/\/bin\/ant.*\$//p"`
+-    else
+-        ANT_HOME="$WITH_ANT_HOME"
+-    fi
+-  else
+-    echo "configure: Ant test failed" >&5
+-    cat conftest.java >&5
+-    cat conftest.xml >&5
+-    AC_MSG_WARN([Ant does not work - Some Java projects will not build!])
+-    ANT_HOME=""
+-    echo "Ant does not work - Some Java projects will not build!" >>warn
+-  fi
+-
+-  rm -f conftest* core core.* *.core
+-fi
+-if test -z "$ANT_HOME"; then
+-   ANT_HOME="NO_ANT_HOME"
+-fi
+-AC_SUBST(ANT_HOME)
+-
+-dnl Checking for ant.jar
+-if test "$ANT_HOME" != "NO_ANT_HOME"; then
+-   AC_MSG_CHECKING([Ant lib directory])
+-   if test -f $ANT_HOME/lib/ant.jar; then
+-	  ANT_LIB="$ANT_HOME/lib"
+-   else
+-      if test -f $ANT_HOME/ant.jar; then
+-	     ANT_LIB="$ANT_HOME"
+-      else
+-          if test -f /usr/share/java/ant.jar; then
+-              ANT_LIB=/usr/share/java
+-          else
+-             if test -f /usr/share/ant-core/lib/ant.jar; then
+-                 ANT_LIB=/usr/share/ant-core/lib
+-             else
+-                 AC_MSG_ERROR([Ant libraries not found!])
+-             fi
+-          fi
+-      fi
+-   fi
+-   AC_MSG_RESULT([Ant lib directory found.])
+-fi
+-AC_SUBST(ANT_LIB)
+-fi
+-
+ AC_MSG_CHECKING([which languages to be built])
+ WITH_LANG="$with_lang"
+ if test -z "$WITH_LANG"; then
+Index: set_soenv.in
+===================================================================
+RCS file: /cvs/tools/config_office/set_soenv.in,v
+retrieving revision 1.48
+diff -u -u -r1.48 set_soenv.in
+--- config_offfice/set_soenv.in	24 Feb 2005 14:44:57 -0000	1.48
++++ config_office/set_soenv.in	11 Mar 2005 10:23:39 -0000
+@@ -1381,9 +1381,6 @@
+    ToFile( "JAVADOC",         "@JAVADOC@",       "e" );
+ }
+ ToFile( "XSLTPROC",          "@XSLTPROC@",       "e" );
+-ToFile( "ANT_HOME",          "@ANT_HOME@",       "e" );
+-ToFile( "ANT_LIB",           "@ANT_LIB@",        "e" );
+-ToFile( "ANT",               "@ANT@",            "e" );
+ ToFile( "JDKLIB",            $JAVA_LIB,          "e" );
+ ToFile( "STLPORT4",          $STLPORT4,          "e" );
+ ToFile( "ASM_PATH",          $ASM_PATH,          "e" );
