Update patches/src680/disable-pam.diff

diff --git a/patches/src680/disable-pam.diff b/patches/src680/disable-pam.diff
--- a/patches/src680/disable-pam.diff
+++ b/patches/src680/disable-pam.diff
@@ -21,8 +21,8 @@
 +    AC_MSG_RESULT([yes])
 +    PAM_LINK=NO
 +    NOPAM=TRUE
-+    dnl TODO: check getspnam_r for needed args (4 or 5)
-+    dnl       and set NEW_SHADOW_API
++    dnl check getspnam_r for needed args (4 or 5)
++    AX_FUNC_WHICH_GETSPNAM_R
 +else
 +    AC_MSG_RESULT([no])
 +    NOPAM=FALSE
@@ -41,11 +41,12 @@
  if test "$_os" = "Linux"; then
 --- config_office/set_soenv.in.orig	2006-04-30 13:45:44.000000000 +0200
 +++ config_office/set_soenv.in	2006-04-30 13:46:11.000000000 +0200
-@@ -1823,6 +1823,7 @@
+@@ -1823,6 +1823,8 @@
  ToFile( "HUNSPELL_CFLAGS",   "@HUNSPELL_CFLAGS@",  "e" );
  ToFile( "SYSTEM_HYPH",       "@SYSTEM_HYPH@",      "e" );
  ToFile( "SYSTEM_MYTHES",     "@SYSTEM_MYTHES@",    "e" );
 +ToFile( "NOPAM",             "@NOPAM@",            "e" );
++ToFile( "NEW_SHADOW_API",    "@NEW_SHADOW_API@",   "e" );
  ToFile( "PAM_LINK",          "@PAM_LINK@",         "e" );
  ToFile( "CRYPT_LINK",        "@CRYPT_LINK@",       "e" );
  ToFile( "GXX_INCLUDE_PATH",  "@GXX_INCLUDE_PATH@", "e" );
@@ -136,3 +137,132 @@
                          {
                              /* if current process is running as root, allow to
                                 logon as any other user */
+--- config_office/aclocal.m4.orig	2006-05-01 20:47:14.000000000 +0200
++++ config_office/aclocal.m4	2006-05-01 22:18:47.000000000 +0200
+@@ -275,3 +275,126 @@
+    echo "$as_me:$LINENO: \$? = $ac_status" >&AS_MESSAGE_LOG_FD
+    (exit $ac_status); }])
+ 
++dnl @synopsis AX_FUNC_WHICH_GETSPNAM_R
++dnl
++dnl Determines which historical variant of the getspnam_r() call
++dnl (taking four or five arguments) is available on the system
++dnl and defines one of the following macros accordingly:
++dnl
++dnl   HAVE_FUNC_GETSPNAM_R_5
++dnl   HAVE_FUNC_GETSPNAM_R_4
++dnl
++dnl Originally named "AX_FUNC_WHICH_GETHOSTBYNAME_R". Rewritten
++dnl for AX_FUNC_WHICH_GETSPNAM_R
++dnl
++dnl @author Caolan McNamara <caolan@skynet.ie>
++dnl @author Daniel Richard G. <skunk@iskunk.org>
++dnl @version 2006-05-01
++dnl @license GPLWithACException
++
++AC_DEFUN([AX_FUNC_WHICH_GETSPNAM_R], [
++
++    AC_LANG_PUSH(C)
++    AC_MSG_CHECKING([how many arguments getspnam_r() takes])
++
++    AC_CACHE_VAL(ac_cv_func_which_getspnam_r, [
++
++################################################################
++
++ac_cv_func_which_getspnam_r=unknown
++
++#
++# ONE ARGUMENT (sanity check)
++#
++
++# This should fail, as there is no variant of getspnam_r() that takes
++# a single argument. If it actually compiles, then we can assume that
++# netdb.h is not declaring the function, and the compiler is thereby
++# assuming an implicit prototype. In which case, we're out of luck.
++#
++AC_COMPILE_IFELSE(
++    AC_LANG_PROGRAM(
++	[[
++	    #include <sys/types.h>
++	    #include <shadow.h>
++	]],
++	[[
++	    const char *name = "myname";
++	    getspnam_r(name) /* ; */
++	]]),
++    ac_cv_func_which_getspnam_r=no)
++
++#
++# FIVE ARGUMENTS
++#
++
++if test "$ac_cv_func_which_getspnam_r" = "unknown"; then
++
++AC_COMPILE_IFELSE(
++    AC_LANG_PROGRAM(
++	[[
++	    #include <sys/types.h>
++	    #include <shadow.h>
++	]],
++	[[
++	    char buffer[[]] = { '\0' };
++	    struct spwd spwdStruct;
++	    const char *name = "myname";
++	    getspnam_r(name, &spwdStruct, buffer, sizeof buffer, 0) /* ; */
++	]]),
++    ac_cv_func_which_getspnam_r=five)
++
++fi
++
++#
++# FOUR ARGUMENTS
++#
++
++if test "$ac_cv_func_which_getspnam_r" = "unknown"; then
++
++AC_COMPILE_IFELSE(
++    AC_LANG_PROGRAM(
++	[[
++	    #include <sys/types.h>
++	    #include <shadow.h>
++	]],
++	[[
++	    char buffer[[]] = { '\0' };
++	    struct spwd spwdStruct;
++	    const char *name = "myname";
++	    getspnam_r(name, &spwdStruct, buffer, sizeof buffer) /* ; */
++	]]),
++    ac_cv_func_which_getspnam_r=four)
++
++fi
++
++################################################################
++
++]) dnl end AC_CACHE_VAL
++
++case "$ac_cv_func_which_getspnam_r" in
++    five)
++    AC_MSG_RESULT([five])
++    AC_SUBST(NEW_SHADOW_API, YES)
++    ;;
++
++    four)
++    AC_MSG_RESULT([four])
++    ;;
++
++    no)
++    AC_MSG_RESULT([cannot find function declaration in shadow.h])
++    ;;
++
++    unknown)
++    AC_MSG_RESULT([can't tell])
++    ;;
++
++    *)
++    AC_MSG_ERROR([internal error])
++    ;;
++esac
++
++AC_LANG_POP(C)
++
++]) dnl end AC_DEFUN
