Merge
* patches/src680/linkoo-rc-dependent-files.diff,
* patches/src680/linkoo-ooenv.diff: merge
* patches/src680/apply: fix m149 issue, re-factor rc
linking, link '/share' too, and intro.bmp.

diff --git a/patches/src680/linkoo-rc-dependent-files.diff b/patches/src680/linkoo-rc-dependent-files.diff
--- a/patches/src680/linkoo-rc-dependent-files.diff
+++ b/patches/src680/linkoo-rc-dependent-files.diff
@@ -1,47 +1,81 @@
---- solenv/bin/linkoo	2005-09-21 16:58:47.000000000 +0530
-+++ solenv/bin/linkoo	2005-10-18 12:31:38.000000000 +0530
-@@ -306,6 +306,36 @@ sub link_types_rdb()
+Index: solenv/bin/linkoo
+===================================================================
+RCS file: /cvs/tools/solenv/bin/linkoo,v
+retrieving revision 1.10
+diff -u -p -u -r1.10 linkoo
+--- solenv/bin/linkoo	14 Dec 2005 14:58:24 -0000	1.10
++++ solenv/bin/linkoo	18 Jan 2006 12:57:29 -0000
+@@ -52,9 +52,13 @@ ulimit -c unlimited
+ export PATH=".:$PATH"
+ export GNOME_DISABLE_CRASH_DIALOG=1
+ export STAR_RESOURCEPATH=`pwd`/resource
++# debugging assistance
++export OOO_FORCE_SYSALLOC=1
++export MALLOC_CHECK_=2
++export OOO_DISABLE_RECOVERY=1
+ ';
+ 
+-my @exceptions = ( 'cppuhelper', 'configmgr', 'cfgmgr', 'sunjavaplugin' );
++my @exceptions = ( 'cppuhelper', 'cfgmgr', 'sunjavaplugin' );
+ 
+ %replaceable = (
+     'program' => '\.so$',
+@@ -139,12 +143,13 @@ sub check_create_linked($)
+     }
+ }
+ 
+-sub do_link($$$$)
++sub do_link($$$$@)
+ {
+     my $src = shift;
+     my $dest = shift;
+     my $src_name = shift;
+     my $dest_name = shift;
++    my $dont_check_link = shift;
+ 
+     if (-l "$dest/$dest_name") {
+ 	my $link = readlink ("$dest/$dest_name");
+@@ -164,7 +169,8 @@ sub do_link($$$$)
+ 	check_create_linked ($dest);
+ 	if (!$dry_run) {
+ 	    # move / write the link
+-	    rename ("$dest/$dest_name", "$dest/linked/$dest_name") || die "Failed rename of $dest/$dest_name: $!";
++	    rename ("$dest/$dest_name", "$dest/linked/$dest_name") ||
++		defined $dont_check_link || die "Failed rename of $dest/$dest_name: $!";
+ 	    symlink ("$src/$src_name", "$dest/$dest_name") || die "Failed to symlink: $!";
+ 	    print " $dest_name";
+ 	} else {
+@@ -279,6 +285,25 @@ sub link_types_rdb()
      print "\n";
  }
  
-+# Hack for soffice.bin and configmgr2.uno.so that depend on rc files
-+sub link_rc_dependent_files()
++# link installed files back into src tree:
++sub link_soffice_bin_files()
 +{
-+    print "soffice.bin case:";
-+    my $src  = "$OOO_BUILD/desktop/$TARGET/bin";
-+    my $dest = "$OOO_INSTALL/program";
-+    if (-l "$src/bootstraprc" && -f (readlink("$src/bootstraprc")) 
-+        && !((readlink ("$src/bootstraprc")) eq "$dest/bootstraprc")) {
-+        print " Existing valid bootstraprc symlink - not overwriting";
-+    } else {
-+        unlink ("$src/bootstraprc");
-+        do_link ($src, $dest, 'soffice', 'soffice.bin');
-+        symlink ("$dest/bootstraprc", "$src/bootstraprc") || die "Failed to symlink: $!";
-+    }
-+    print "\n";
++    my $dest;
++    my $src = "$OOO_INSTALL/program";
 +
-+    print "configmgr2.uno.so case:";
-+    my $src  = "$OOO_BUILD/configmgr/$TARGET/lib";
-+    my $dest = "$OOO_INSTALL/program";
-+    if (-l "$src/configmgrrc" && -f (readlink("$src/configmgrrc")) 
-+        && !((readlink ("$src/configmgrrc")) eq "$dest/configmgrrc")) {
-+        print " Existing valid configmgrrc symlink - not overwriting";
-+    } else {
-+        unlink ("$src/configmgrrc");
-+        do_link ($src, $dest, 'configmgr2.uno.so', 'configmgr2.uno.so');
-+        symlink ("$dest/configmgrrc", "$src/configmgrrc") || die "Failed to symlink: $!";
-+    }
++    print "soffice files";
++    $dest = "$OOO_BUILD/desktop/$TARGET/bin";
++    do_link ($src, $dest, 'soffice', 'soffice.bin', 1);
++    do_link ($src, $dest, 'bootstraprc', 'bootstraprc', 1);
++    do_link ($src, $dest, 'intro.bmp', 'intro.bmp', 1);
++    do_link ("$OOO_INSTALL", "$OOO_BUILD/desktop/$TARGET", 'share', 'share', 1);
++
++    $dest = "$OOO_BUILD/configmgr/$TARGET/lib";
++    do_link ($src, $dest, 'configmgrrc', 'configmgrrc', 1);
++
 +    print "\n";
 +}
 +
  my $a;
  my $usage = 0;
  for $a (@ARGV) {
-@@ -355,6 +385,7 @@ my $installed_files = build_installed_li
+@@ -328,6 +353,7 @@ my $installed_files = build_installed_li
  scan_and_link_files ($OOO_BUILD, $installed_files, $TARGET);
  link_iso_res();
  link_types_rdb();
-+link_rc_dependent_files();
++link_soffice_bin_files();
  
  if (!-f "$OOO_INSTALL/program/ooenv") {
      print "Creating '$OOO_INSTALL/program/ooenv'\n";
